window.LHB_EVENTS = [
  {
    id: "evt-001",
    title: "中国国际进口博览会",
    city: "上海",
    venue: "国家会展中心（上海）",
    type: "展会",
    rank: "S",
    status: "即将开始",
    startDate: "2026-11-05",
    endDate: "2026-11-10",
    industries: ["商场", "食品饮料", "美妆", "3C数码", "珠宝奢侈品"],
    brands: ["国际品牌", "消费品展区", "技术装备展区"],
    host: "中国国际进口博览局",
    summary: "综合型头部展会，消费品、食品、技术装备等品牌集中，适合做高质量专题和商务线索承接。",
    highlights: ["国际品牌集中", "大型商业合作入口", "适合专题化运营"],
    fitProducts: ["品牌引入", "体验设计", "活动专题", "合作线索"],
    source: "https://www.ciie.org/",
    sourceLabel: "中国国际进口博览会",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-002",
    title: "上海国际美妆供应链博览会",
    city: "上海",
    venue: "上海新国际博览中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    industries: ["美妆", "香氛", "洗护"],
    brands: ["国货美妆", "香氛品牌", "供应链企业"],
    host: "行业展会主办方",
    summary: "覆盖美妆、香氛、洗护与供应链，适合寻找线下体验、快闪试用和新品牌首店机会。",
    highlights: ["美妆香氛密集", "适合品牌首店观察", "内容深挖空间大"],
    fitProducts: ["快闪体验", "慢闪首店", "体验SOP"],
    source: "https://www.chinabeautyexpo.com/",
    sourceLabel: "中国美容博览会",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-003",
    title: "杭州国际数字生活博览会",
    city: "杭州",
    venue: "杭州大会展中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-09-18",
    endDate: "2026-09-21",
    industries: ["3C数码", "游戏/App", "商场"],
    brands: ["智能硬件", "数字生活", "消费科技"],
    host: "数字经济相关机构",
    summary: "面向数字生活和消费科技场景，适合寻找智能硬件、新品体验和数字化零售合作线索。",
    highlights: ["杭州数字经济优势", "智能硬件集中", "适合体验店模型"],
    fitProducts: ["慢闪体验", "新品测试", "数智化选址"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: false,
    isHeadline: true
  },
  {
    id: "evt-004",
    title: "广州国际美博会",
    city: "广州",
    venue: "中国进出口商品交易会展馆",
    type: "展会",
    rank: "S",
    status: "筹备中",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    industries: ["美妆", "香氛", "洗护", "保健品"],
    brands: ["美妆品牌", "香氛品牌", "个护企业"],
    host: "美博会主办方",
    summary: "华南美妆个护头部展会，品牌密度和渠道资源强，适合做行业专题与招商线索。",
    highlights: ["美妆个护头部场", "品牌与渠道集中", "商业化空间高"],
    fitProducts: ["行业专题", "快闪体验", "品牌合作"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-005",
    title: "深圳国际消费电子展",
    city: "深圳",
    venue: "深圳会展中心",
    type: "展会",
    rank: "S",
    status: "筹备中",
    startDate: "2026-04-09",
    endDate: "2026-04-11",
    industries: ["3C数码", "游戏/App", "家居家装"],
    brands: ["智能硬件", "影像设备", "智能家居"],
    host: "消费电子展会主办方",
    summary: "消费电子与智能硬件密集场，适合挖掘新品体验、旗舰店升级和线下首店机会。",
    highlights: ["深圳硬件供应链", "新品体验需求强", "适合头部曝光"],
    fitProducts: ["新品测试", "体验设计", "慢闪首店"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: false,
    isHeadline: true
  },
  {
    id: "evt-006",
    title: "北京国际潮流玩具展",
    city: "北京",
    venue: "北京展览馆",
    type: "展会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-08-22",
    endDate: "2026-08-24",
    industries: ["潮玩", "IP类", "游戏/App"],
    brands: ["潮玩品牌", "游戏IP", "文创IP"],
    host: "潮玩展会主办方",
    summary: "潮玩和IP线下消费场景集中，适合寻找IP快闪、主题慢闪和商场联名合作。",
    highlights: ["IP密度高", "适合商场合作", "年轻客群清晰"],
    fitProducts: ["IP快闪", "场景策展", "主题慢闪"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-007",
    title: "上海城市户外生活节",
    city: "上海",
    venue: "黄浦滨江",
    type: "体验活动",
    rank: "A",
    status: "进行中",
    startDate: "2026-06-20",
    endDate: "2026-07-05",
    industries: ["运动户外", "鞋服", "食品饮料"],
    brands: ["户外品牌", "运动鞋服", "咖啡饮品"],
    host: "城市活动运营方",
    summary: "户外生活方式场景活动，适合观察运动户外品牌的城市快闪、体验营销和社群转化。",
    highlights: ["户外生活方式", "城市公共空间", "适合快闪体验"],
    fitProducts: ["快闪新品", "慢闪测试", "社群活动"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-008",
    title: "杭州新消费品牌快闪季",
    city: "杭州",
    venue: "湖滨商圈",
    type: "快闪",
    rank: "B",
    status: "进行中",
    startDate: "2026-06-15",
    endDate: "2026-07-15",
    industries: ["香氛", "美妆", "食品饮料", "鞋服"],
    brands: ["新消费品牌", "生活方式品牌"],
    host: "商圈运营方",
    summary: "多品牌快闪集合活动，适合测试新锐品牌线下转化和商圈客流匹配。",
    highlights: ["新消费密集", "湖滨商圈", "适合小样本验证"],
    fitProducts: ["快闪体验", "市场调研", "首店测试"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-009",
    title: "广州餐饮连锁加盟展",
    city: "广州",
    venue: "保利世贸博览馆",
    type: "招商会",
    rank: "B",
    status: "筹备中",
    startDate: "2026-07-26",
    endDate: "2026-07-28",
    industries: ["茶饮连锁", "餐厅", "食品饮料"],
    brands: ["茶饮品牌", "连锁餐饮", "供应链企业"],
    host: "餐饮展会主办方",
    summary: "餐饮和茶饮连锁招商场，适合数智化选址、网规拓店和竞品监测切入。",
    highlights: ["连锁餐饮集中", "加盟拓店诉求强", "适合选址产品"],
    fitProducts: ["数智化选址", "网规拓店", "竞品监测"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: false,
    isHeadline: false
  },
  {
    id: "evt-010",
    title: "深圳智能家居体验周",
    city: "深圳",
    venue: "南山科技园",
    type: "体验活动",
    rank: "B",
    status: "即将开始",
    startDate: "2026-07-08",
    endDate: "2026-07-14",
    industries: ["3C数码", "家居家装"],
    brands: ["智能家居", "清洁电器", "影音设备"],
    host: "科技园区运营方",
    summary: "智能家居体验型活动，适合智能硬件品牌做线下体验、场景设计和首店模型验证。",
    highlights: ["体验驱动", "智能硬件聚集", "适合模型验证"],
    fitProducts: ["慢闪体验", "体验设计", "市场调研"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-011",
    title: "北京购物中心商业更新论坛",
    city: "北京",
    venue: "朝阳区会议中心",
    type: "峰会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-09-06",
    endDate: "2026-09-07",
    industries: ["商场", "IP类", "运动户外", "潮玩"],
    brands: ["购物中心", "商业地产", "品牌方"],
    host: "商业地产媒体",
    summary: "商业地产与购物中心更新议题集中，适合品牌引入、空间招商和快闪合作资源对接。",
    highlights: ["商场决策者集中", "空间更新议题", "合作入口清晰"],
    fitProducts: ["品牌引入", "空间招商", "IP快闪"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: false,
    isHeadline: true
  },
  {
    id: "evt-012",
    title: "上海香氛生活方式快闪",
    city: "上海",
    venue: "武康路街区",
    type: "快闪",
    rank: "B",
    status: "历史",
    startDate: "2026-04-12",
    endDate: "2026-04-28",
    industries: ["香氛", "美妆", "商场"],
    brands: ["沙龙香", "国货香氛", "生活方式品牌"],
    host: "街区商业运营方",
    summary: "香氛生活方式快闪，已结束但具备历史归档和案例参考价值。",
    highlights: ["历史案例", "街区场景", "适合复盘"],
    fitProducts: ["慢闪体验", "五感设计", "案例复盘"],
    source: "待核验",
    sourceLabel: "待补充",
    isNew: false,
    isHeadline: false
  }
];
