window.FRESH_ACTIVITIES = [
  {
    id: "evt-107",
    title: "第28届亚洲宠物展 PFA2026",
    city: "上海",
    venue: "上海新国际博览中心",
    type: "展会",
    rank: "S",
    status: "筹备中",
    startDate: "2026-08-19",
    endDate: "2026-08-23",
    industries: ["宠物", "食品饮料", "商场"],
    brands: ["宠物食品品牌", "宠物用品品牌", "宠物医疗服务", "内容平台"],
    host: "亚洲宠物展",
    summary: "亚洲宠物展官网确认第28届亚洲宠物展将于2026年8月19-23日在上海新国际博览中心举办，定位为亚太宠物行业旗舰展，覆盖宠物上下游全产业链。",
    highlights: ["官方确认档期", "32万平方米展出面积", "2600+展商", "宠物行业旗舰展"],
    fitProducts: ["品牌合作", "快闪体验", "渠道线索", "商场宠物主题活动"],
    audience: ["宠物品牌", "渠道商", "专业买家", "宠物服务商", "内容平台"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "市场负责人", "平台招商负责人"],
    representativeBrands: ["瑞鹏宠物", "疯狂小狗", "麦富迪", "京东", "抖音生活服务", "天猫", "小红书"],
    scale: "官网披露：32万平方米展出面积，2600+展商，13万+专业观众，39万+消费者。",
    ticketInfo: "官网提供专业观众预登记、消费者参观购票和同期会议报名入口。",
    participation: "建议会前按宠物食品、用品、医疗、内容平台四类拆分品牌线索，优先约品牌市场和渠道负责人。",
    buSuggestion: ["宠物行业BD", "商场主题活动", "品牌快闪"],
    leadAngle: "围绕宠物品牌线下体验、商场宠物友好主题活动、渠道招商和内容平台合作切入。",
    mediaAccounts: ["亚洲宠物展", "宠业家", "宠物行业白皮书", "小红书", "抖音生活服务"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.petfairasia.com/",
    sourceLabel: "亚洲宠物展官网",
    sourceFacts: [
      "官网首页显示第28届亚洲宠物展时间为2026年8月19-23日，地点为上海新国际博览中心。",
      "官网披露展出面积32万平方米、2600+展商、13万+专业观众和39万+消费者。",
      "官网列出专业观众预登记、消费者购票、同期会议报名等入口。"
    ],
    lhbNotes: [
      "宠物品牌对线下体验和商场宠物友好空间有天然需求，建议设为S级重点专题。",
      "官网已列出合作品牌与平台入口，后续应继续补抓展商明细并沉淀可BD品牌名单。"
    ],
    missingFields: ["完整展商名单", "具体议程", "官方现场图片"],
    contentSections: [
      { title: "官方展会介绍", body: "第28届亚洲宠物展以超大规模覆盖宠物上下游全产业链，并将首日打造为邀请制VIP专业日，强化专业买家、海外买家、渠道商、媒体和品牌之间的高密度商务洽谈。" },
      { title: "LHB匹配判断", body: "宠物食品、宠物用品和宠物服务品牌需要线下试用、社区触达、商场宠物友好场景和达人内容联动，适合切入快闪体验、商场主题活动和品牌合作。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-108",
    title: "2026亚洲宠物供应链展",
    city: "上海",
    venue: "上海新国际博览中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-08-19",
    endDate: "2026-08-21",
    industries: ["宠物", "食品饮料", "家居家装"],
    brands: ["宠物食品供应链", "宠物用品工厂", "包装企业", "跨境品牌"],
    host: "亚洲宠物展",
    summary: "亚洲宠物展官网系列展览中列出亚洲宠物供应链展，2026年8月19-21日在上海新国际博览中心举办，适合补充宠物行业供应链和品牌源头线索。",
    highlights: ["亚宠同期", "供应链展", "源头工厂线索"],
    fitProducts: ["渠道线索", "品牌合作", "数据服务"],
    audience: ["源头工厂", "宠物品牌", "渠道商", "跨境卖家"],
    attendeeRoles: ["品牌负责人", "供应链负责人", "渠道负责人", "采购负责人"],
    representativeBrands: ["宠物食品供应链", "宠物用品工厂", "包装企业"],
    scale: "官网作为亚洲宠物展系列展列出，具体供应链展独立规模待补。",
    ticketInfo: "以亚洲宠物展官网专业观众预登记和同期会议报名入口为准。",
    participation: "建议与亚洲宠物展主展联动参观，重点补抓源头工厂和新锐宠物品牌。",
    buSuggestion: ["宠物行业BD", "渠道线索", "品牌合作"],
    leadAngle: "围绕宠物供应链品牌孵化、渠道开拓和新品牌线下测试切入。",
    mediaAccounts: ["亚洲宠物展", "宠业家", "宠物供应链媒体"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.petfairasia.com/",
    sourceLabel: "亚洲宠物展官网系列展",
    sourceFacts: [
      "亚洲宠物展官网系列展览显示亚洲宠物供应链展时间为2026年8月19-21日，地点为上海新国际博览中心。",
      "该展与PFA2026同期，适合与主展一起做宠物行业线索池。"
    ],
    lhbNotes: ["优先沉淀宠物源头工厂、新锐品牌和跨境品牌的线下首发、快闪试销需求。"],
    missingFields: ["独立展商名单", "独立议程", "官方现场图片"],
    contentSections: [
      { title: "官方线索", body: "该活动来自亚洲宠物展官网系列展列表，当前已确认时间、地点和同期关系，独立展区介绍需继续补充。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-109",
    title: "2026华南宠物用品展 PFSC2026",
    city: "广州",
    venue: "中国进出口商品交易会展馆（琶洲展馆）",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-12-11",
    endDate: "2026-12-13",
    industries: ["宠物", "食品饮料", "商场"],
    brands: ["宠物食品品牌", "宠物用品品牌", "华南渠道商"],
    host: "亚洲宠物展",
    summary: "亚洲宠物展官网系列展览中列出华南宠物用品展PFSC2026，将于2026年12月11-13日在中国进出口商品交易会（琶洲展馆）举办。",
    highlights: ["官方确认档期", "华南宠物渠道", "广州重点城市"],
    fitProducts: ["品牌快闪", "渠道线索", "商场主题活动"],
    audience: ["宠物品牌", "华南渠道商", "宠物门店", "供应链企业"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "门店运营负责人"],
    representativeBrands: ["宠物食品品牌", "宠物用品品牌", "华南渠道商"],
    scale: "作为亚洲宠物展系列展，独立规模待官方详情页补充。",
    ticketInfo: "以亚洲宠物展官网系列展报名入口为准。",
    participation: "建议作为广州其他城市宠物活动储备，补足华南品牌与渠道线索。",
    buSuggestion: ["宠物行业BD", "广州城市BD", "商场主题活动"],
    leadAngle: "围绕华南宠物品牌线下体验、商场宠物主题活动和渠道招商切入。",
    mediaAccounts: ["亚洲宠物展", "华南宠物用品展", "宠物行业媒体"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.petfairasia.com/",
    sourceLabel: "亚洲宠物展官网系列展",
    sourceFacts: [
      "亚洲宠物展官网系列展览显示华南宠物用品展PFSC2026时间为2026年12月11-13日。",
      "官网显示举办地点为中国进出口商品交易会（琶洲展馆）。"
    ],
    lhbNotes: ["广州宠物活动可以补充非上海宠物行业覆盖，利于城市分布和华南渠道线索。"],
    missingFields: ["独立展商名单", "具体议程", "官方现场图片"],
    contentSections: [
      { title: "官方线索", body: "该活动来自亚洲宠物展官网系列展列表，已确认城市、时间和场馆；后续需要继续补充独立活动页、展商名单和报名入口。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-110",
    title: "2026CBME国际孕婴童展",
    city: "上海",
    venue: "国家会展中心（上海）",
    type: "展会",
    rank: "S",
    status: "即将开始",
    startDate: "2026-07-15",
    endDate: "2026-07-17",
    industries: ["母婴", "食品饮料", "潮玩", "IP类", "家居家装"],
    brands: ["孕婴童用品品牌", "童装品牌", "玩具教育品牌", "营养健康食品品牌"],
    host: "亿百媒会展（上海）有限公司",
    summary: "CBME官网确认2026 CBME国际孕婴童展将于2026年7月15-17日在上海国家会展中心举行，同期举办玩具及教育展、童装展、营养健康食品展、智能制造展和全球授权展·上海站。",
    highlights: ["官方确认档期", "母婴全渠道商贸平台", "4300+品牌", "同期全球授权展"],
    fitProducts: ["品牌合作", "IP快闪", "亲子主题活动", "商场招商"],
    audience: ["孕婴童品牌", "玩具教育品牌", "童装品牌", "营养健康食品品牌", "渠道商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "市场负责人", "采购负责人", "IP授权负责人"],
    representativeBrands: ["babycare", "宝宝树", "贝恩施", "布朗博士", "德佑", "童年故事"],
    scale: "官网显示与4300+全球优质品牌同台展示，覆盖用品、食品、童装、玩教、童车汽座、智能制造等板块。",
    ticketInfo: "官网提供观众报名、展位预订、展商查询和产品查询入口。",
    participation: "建议立即作为即将开始活动跟进，重点补品牌展位、IP授权和亲子场景合作机会。",
    buSuggestion: ["母婴BD", "IP快闪", "商场亲子主题"],
    leadAngle: "围绕母婴品牌线下体验、亲子主题商场活动、IP授权和食品试吃试饮切入。",
    mediaAccounts: ["CBME国际孕婴童展", "母婴行业观察", "玩具前沿", "IP授权媒体"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.cbmexpo.com/",
    sourceLabel: "CBME官网",
    sourceFacts: [
      "CBME官网显示展会倒计时日期为2026年7月15-17日。",
      "官网介绍显示2026 CBME将在上海国家会展中心举行。",
      "官网说明同期举办CBME玩具及教育展、CBME童装展、CBME营养健康食品展、CBME智能制造展和全球授权展·上海站。"
    ],
    lhbNotes: [
      "该活动距离当前日期很近，应进入头部即将开始专题。",
      "母婴、玩教、童装、营养健康食品和IP授权都与LHB商场亲子主题活动、快闪体验高度匹配。"
    ],
    missingFields: ["完整展商名单下载", "具体论坛议程", "官方现场图片"],
    contentSections: [
      { title: "官方展会介绍", body: "CBME国际孕婴童展始于2001年，是全球专业孕婴童全渠道商贸对接平台。2026年展会覆盖母婴用品、孕婴童食品、婴童装童鞋配饰、玩具及教育、童车汽座、智能制造等板块。" },
      { title: "LHB匹配判断", body: "该展的品牌类型天然适合亲子商场、IP联名、玩具教育体验、母婴食品试吃和童装快闪等线下业务，建议优先补展商名单并建立会前拜访清单。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-111",
    title: "2026全球授权展·上海站（LEC）",
    city: "上海",
    venue: "国家会展中心（上海）",
    type: "展会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-07-15",
    endDate: "2026-07-17",
    industries: ["IP类", "潮玩", "母婴", "商场"],
    brands: ["IP授权方", "玩具品牌", "母婴品牌", "内容平台"],
    host: "CBME同期展",
    summary: "CBME官网展位分布和展会介绍中列出全球授权展·上海站（LEC），与2026 CBME在7月15-17日同期举行，适合补充IP授权、亲子内容和商场主题活动线索。",
    highlights: ["CBME同期展", "IP授权", "亲子内容", "商场主题活动"],
    fitProducts: ["IP快闪", "商场主题展", "品牌联名", "亲子活动"],
    audience: ["IP授权方", "玩具品牌", "母婴品牌", "商场活动方"],
    attendeeRoles: ["IP授权负责人", "品牌市场负责人", "渠道负责人", "平台招商负责人"],
    representativeBrands: ["玩具教育品牌", "母婴品牌", "IP授权方"],
    scale: "随CBME同期举办，独立规模待LEC详情页补充。",
    ticketInfo: "以CBME官网观众报名入口为准。",
    participation: "建议与CBME主展联动跟进，重点筛IP授权负责人、玩具教育品牌和商场亲子活动资源。",
    buSuggestion: ["IP快闪", "商场活动", "品牌联名"],
    leadAngle: "围绕IP授权、亲子主题快闪、商场互动展和品牌联名切入。",
    mediaAccounts: ["CBME国际孕婴童展", "全球授权展", "IP授权媒体"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.cbmexpo.com/",
    sourceLabel: "CBME官网展会介绍",
    sourceFacts: [
      "CBME官网介绍列出全球授权展·上海站（LEC）为2026 CBME同期展。",
      "CBME官网展位分布图板块也显示全球授权展·上海站。"
    ],
    lhbNotes: ["IP授权是LHB快闪和商场主题活动的关键上游来源，建议单独入库跟踪。"],
    missingFields: ["LEC独立活动页", "IP展商名单", "官方现场图片"],
    contentSections: [
      { title: "官方线索", body: "该活动来自CBME官网同期活动信息，已确认与CBME同期开启；后续需补抓独立活动页、IP展商和授权品牌名单。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-112",
    title: "第31届CBE中国美容博览会（上海）",
    city: "上海",
    venue: "上海新国际博览中心",
    type: "展会",
    rank: "S",
    status: "筹备中",
    startDate: "2027-05-12",
    endDate: "2027-05-14",
    industries: ["美妆", "香氛", "洗护", "母婴"],
    brands: ["美妆品牌", "香氛品牌", "个护品牌", "美妆供应链"],
    host: "CBE中国美容博览会",
    summary: "CBE官网顶部显示CBE Shanghai下一届时间为2027年5月12-14日，并在官网介绍中说明CBE覆盖美妆供应链、个人护理、彩妆香氛、婴童护理、家清等品类。",
    highlights: ["官方下一届档期", "美妆头部展", "香氛个护重点行业", "供应链+品牌双覆盖"],
    fitProducts: ["美妆快闪", "香氛体验", "品牌合作", "商场招商"],
    audience: ["美妆品牌", "香氛品牌", "个护品牌", "美妆供应链", "渠道商"],
    attendeeRoles: ["品牌负责人", "市场负责人", "渠道负责人", "采购负责人", "供应链负责人"],
    representativeBrands: ["Shanghai Herynn Fragrance & Flavors", "Shenzhen Winkey Technology", "Guangzhou Ridgepole Biological Technology", "A&H International Cosmetics"],
    scale: "CBE官网说明2026届曾汇聚3200+展商，其中1500+企业覆盖OEM/ODM、原料、包装和设备；2027届具体规模待更新。",
    ticketInfo: "官网提供Visitor Registration和Book Your Stand入口。",
    participation: "建议作为2027美妆香氛头部储备，提前建立品牌展商和供应链名单。",
    buSuggestion: ["美妆香氛BD", "快闪体验", "品牌合作"],
    leadAngle: "围绕美妆香氛新品体验、商场快闪、品牌联名和渠道招商切入。",
    mediaAccounts: ["CBE中国美容博览会", "美妆头条", "聚美丽", "品观"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.chinabeautyexpo.com/",
    sourceLabel: "CBE官网",
    sourceFacts: [
      "CBE官网顶部显示CBE Shanghai日期为May 12-14, 2027。",
      "官网介绍显示CBE覆盖personal care、skincare、color cosmetics、perfume & fragrances、baby care、household cleaning等品类。",
      "官网说明CBE 2026曾汇聚3200+展商，其中1500+覆盖OEM/ODM、原料、包装和设备。"
    ],
    lhbNotes: [
      "这是美妆香氛行业的S级未来储备活动，适合持续补抓展商和品牌名单。",
      "因时间在2027年，当前状态会自动计算为筹备中。"
    ],
    missingFields: ["2027完整展商名单", "2027议程", "官方现场图片"],
    contentSections: [
      { title: "官方展会介绍", body: "CBE是美妆供应链和品牌B2B平台，覆盖个人护理、护肤、彩妆、香水香氛、婴童护理、家清及相关服务，是美妆香氛品牌线下体验和渠道合作的重要场景。" },
      { title: "LHB匹配判断", body: "美妆、香氛、洗护品牌对新品体验、快闪试用和商场曝光需求强，适合提前做会前品牌池和会后重点品牌跟进。" }
    ],
    updatedAt: "2026-07-08",
    isNew: true,
    isHeadline: true
  }
];

window.ACTIVITY_ENRICHMENTS = {
  ...(window.ACTIVITY_ENRICHMENTS || {}),
  "evt-054": {
    host: "中国对外贸易中心集团有限公司、中国建筑装饰协会",
    summary: "中国建博会（广州）官网确认第28届中国（广州）国际建筑装饰博览会于2026年7月8-11日在广交会展馆举办，由中国对外贸易中心集团有限公司、中国建筑装饰协会主办，中国对外贸易广州展览有限公司承办。官方介绍强调以“冠军企业首秀平台”为定位，设置室内空间、门窗户外、材艺智造三大场域，并深化经销商、设计师、装企、商业公装、新媒体等渠道。",
    scale: "官网披露：2026届参展企业近2000家，预计吸引超过100个国家和地区约20万名高质量专业观众；2025届展览面积约30万平方米、专业观众205621人。",
    ticketInfo: "官网提供预约登记和参展申请入口。",
    participation: "该活动已在2026年7月8日开幕，当前应按进行中处理；建议优先抓会期新闻、主题活动和参展品牌，形成家居建材线索池。",
    source: "https://www.cbdfair-gz.com/",
    sourceLabel: "中国建博会（广州）官网",
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    sourceFacts: [
      "官网显示第28届中国（广州）国际建筑装饰博览会时间为2026年7月8-11日，地点为广州广交会展馆。",
      "官网披露主办方为中国对外贸易中心集团有限公司、中国建筑装饰协会。",
      "官网披露本届参展企业近2000家，预计超过100个国家和地区约20万名高质量专业观众到会。"
    ],
    lhbNotes: [
      "该活动在当前日期2026年7月8日处于进行中，应优先补抓现场新闻和参展品牌。",
      "家居建材品牌适合切入慢闪体验、门店场景展示、商场招商和设计师渠道合作。"
    ],
    contentSections: [
      { title: "官方展会介绍", body: "中国建博会（广州）以冠军企业首秀平台为定位，2026届创新推出室内空间、门窗户外、材艺智造三大场域，并深化经销商、外贸、设计师、装企、商业公装、新媒体等六大渠道建设。" },
      { title: "LHB匹配判断", body: "家居建材品牌具备展示场景强、门店体验重、渠道招商明显的特点，适合切入慢闪店、商场家居场景展、设计师渠道活动和品牌合作。" }
    ],
    updatedAt: "2026-07-08"
  }
};
