window.HUODONGXING_ACTIVITIES = [
  {
    id: "evt-hdx-001",
    title: "2026品牌全球化进化营-深圳站",
    city: "深圳",
    venue: "深圳，具体场馆待补充",
    type: "沙龙",
    rank: "A",
    status: "即将开始",
    startDate: "2026-07-25",
    endDate: "2026-07-26",
    industries: ["商场", "食品饮料", "美妆", "鞋服", "3C数码"],
    brands: ["出海品牌", "新消费品牌", "跨境电商品牌", "品牌服务商"],
    host: "活动行公开活动页待补充",
    summary: "活动行公开列表出现“2026品牌全球化进化营-深圳站”。该活动适合补充品牌方、出海品牌和新消费品牌的线索，尤其适合围绕线下快闪、首店试验和品牌联名合作切入。",
    highlights: ["品牌全球化", "深圳品牌线索", "活动行来源"],
    fitProducts: ["品牌合作", "快闪体验", "渠道线索", "市场调研"],
    audience: ["出海品牌", "新消费品牌", "品牌营销负责人", "跨境电商负责人"],
    attendeeRoles: ["创始人", "品牌负责人", "市场负责人", "渠道负责人"],
    representativeBrands: ["出海品牌", "新消费品牌", "跨境电商品牌"],
    scale: "活动行公开列表未展示规模，需进入详情页或主办方渠道补充",
    ticketInfo: "活动行公开列表显示可报名，具体票务待补充",
    participation: "建议报名或联系主办方获取参会品牌名单，作为深圳品牌全球化线索池",
    buSuggestion: ["品牌BD", "快闪体验", "渠道线索"],
    leadAngle: "围绕品牌出海前后的线下体验、国内标杆商圈快闪、品牌联名活动和渠道验证切入。",
    mediaAccounts: ["活动行", "品牌全球化相关媒体"],
    sourceType: "活动行",
    sourceConfidence: "高",
    source: "https://www.huodongxing.com/",
    sourceLabel: "活动行公开列表",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["活动行公开首页/列表出现该活动名称及排期线索。", "当前仅抓到列表级信息，主办方、场馆、完整议程和参会品牌需二次补充。"],
    lhbNotes: ["深圳为首批重点城市，品牌全球化活动可触达消费品牌和跨境品牌负责人。", "更适合进入BD线索池，不宜直接作为头部专题。"],
    missingFields: ["活动行详情页", "准确场馆", "主办方", "票务信息", "参会品牌名单", "官方图片"],
    contentSections: [{ title: "活动行列表摘要", body: "该活动作为品牌全球化主题线索，适合从品牌拓展、快闪体验和线下合作角度继续深挖。" }],
    updatedAt: "2026-06-28",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-hdx-002",
    title: "2026选品会-汕头站",
    city: "汕头",
    venue: "汕头，具体场馆待补充",
    type: "选品会",
    rank: "B",
    status: "即将开始",
    startDate: "2026-07-25",
    endDate: "2026-07-25",
    industries: ["食品饮料", "商场", "母婴", "潮玩", "IP类"],
    brands: ["源头工厂", "消费品品牌", "渠道商", "供应链企业"],
    host: "活动行公开活动页待补充",
    summary: "活动行公开列表出现“2026选品会-汕头站”。汕头具备玩具、食品和消费品产业带基础，可作为其他城市品牌和供应链线索补充。",
    highlights: ["选品会", "产业带线索", "其他城市补充"],
    fitProducts: ["渠道线索", "品牌合作", "市场调研"],
    audience: ["消费品品牌", "渠道商", "采购负责人", "供应链企业"],
    attendeeRoles: ["采购负责人", "渠道负责人", "品牌负责人", "招商负责人"],
    representativeBrands: ["产业带消费品牌", "玩具/IP供应链", "食品品牌"],
    scale: "活动行公开列表未展示规模，需补充",
    ticketInfo: "待补充活动行报名信息",
    participation: "建议作为产业带品牌线索补充，筛选适合商场快闪和渠道合作的品牌",
    buSuggestion: ["渠道线索", "IP/潮玩BD", "食品饮料BD"],
    leadAngle: "围绕产业带品牌筛选、商场快闪试卖、渠道选品和品牌合作切入。",
    mediaAccounts: ["活动行", "选品会相关主办方"],
    sourceType: "活动行",
    sourceConfidence: "高",
    source: "https://www.huodongxing.com/",
    sourceLabel: "活动行公开列表",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["活动行公开首页/列表出现该活动名称及排期线索。", "当前仅抓到列表级信息。"],
    lhbNotes: ["汕头不在首批五城，但产业带品牌与LHB品牌线索沉淀相关。"],
    missingFields: ["活动行详情页", "准确场馆", "主办方", "展商/品牌名单", "票务信息", "官方图片"],
    contentSections: [{ title: "活动行列表摘要", body: "该活动更偏渠道选品与产业带品牌发现，适合进入其他城市线索池。" }],
    updatedAt: "2026-06-28",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-hdx-003",
    title: "2026跨境大卖增长论坛暨产业链交流活动",
    city: "杭州",
    venue: "杭州，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-07-29",
    endDate: "2026-07-29",
    industries: ["商场", "食品饮料", "美妆", "3C数码", "鞋服"],
    brands: ["跨境大卖", "消费品品牌", "供应链服务商", "品牌服务商"],
    host: "活动行公开活动页待补充",
    summary: "活动行公开列表出现“2026跨境大卖增长论坛暨产业链交流活动”。杭州品牌、电商和服务商生态强，适合挖掘消费品牌增长、选品和线下体验合作线索。",
    highlights: ["跨境大卖", "杭州重点城市", "品牌增长"],
    fitProducts: ["品牌合作", "渠道线索", "市场调研", "快闪体验"],
    audience: ["跨境电商品牌", "消费品品牌", "供应链企业", "营销服务商"],
    attendeeRoles: ["创始人", "品牌负责人", "增长负责人", "渠道负责人"],
    representativeBrands: ["跨境大卖", "消费品品牌", "供应链服务商"],
    scale: "活动行公开列表未展示规模，需补充",
    ticketInfo: "待补充活动行报名信息",
    participation: "建议用于杭州品牌增长与跨境消费品线索补充",
    buSuggestion: ["品牌BD", "渠道线索", "市场调研"],
    leadAngle: "围绕消费品牌国内线下测试、快闪试卖、商圈场景验证和渠道合作切入。",
    mediaAccounts: ["活动行", "跨境电商行业媒体"],
    sourceType: "活动行",
    sourceConfidence: "高",
    source: "https://www.huodongxing.com/",
    sourceLabel: "活动行公开列表",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["活动行公开首页/列表出现该活动名称及排期线索。", "当前仅抓到列表级信息。"],
    lhbNotes: ["杭州是首批重点城市，跨境消费品牌可能存在国内线下体验和品牌活动需求。"],
    missingFields: ["活动行详情页", "准确场馆", "主办方", "嘉宾名单", "票务信息", "官方图片"],
    contentSections: [{ title: "活动行列表摘要", body: "该活动匹配品牌增长、跨境消费品和渠道资源，建议后续进入详情页补充议程和参会品牌。" }],
    updatedAt: "2026-06-28",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-hdx-004",
    title: "2026全球数贸会电商创新发展峰会",
    city: "杭州",
    venue: "杭州，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-07-31",
    endDate: "2026-07-31",
    industries: ["商场", "食品饮料", "美妆", "3C数码", "茶饮连锁"],
    brands: ["电商品牌", "新消费品牌", "平台服务商", "渠道服务商"],
    host: "活动行公开活动页待补充",
    summary: "活动行公开列表出现“2026全球数贸会电商创新发展峰会”。该活动与电商品牌、平台服务商和消费品牌增长相关，适合作为杭州品牌线索补充。",
    highlights: ["电商创新", "杭州重点城市", "消费品牌"],
    fitProducts: ["品牌合作", "渠道线索", "市场调研"],
    audience: ["电商品牌", "平台服务商", "新消费品牌", "渠道服务商"],
    attendeeRoles: ["品牌负责人", "增长负责人", "渠道负责人", "平台运营负责人"],
    representativeBrands: ["电商品牌", "新消费品牌", "平台服务商"],
    scale: "活动行公开列表未展示规模，需补充",
    ticketInfo: "待补充活动行报名信息",
    participation: "建议作为杭州品牌增长线索补充，优先补完整议程和参会品牌",
    buSuggestion: ["品牌BD", "渠道线索", "市场调研"],
    leadAngle: "围绕线上品牌线下化、商场快闪、渠道验证和场景活动合作切入。",
    mediaAccounts: ["活动行", "数贸会相关媒体"],
    sourceType: "活动行",
    sourceConfidence: "高",
    source: "https://www.huodongxing.com/",
    sourceLabel: "活动行公开列表",
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["活动行公开首页/列表出现该活动名称及排期线索。", "当前仅抓到列表级信息。"],
    lhbNotes: ["电商创新活动可补线上消费品牌向线下体验延展的机会。"],
    missingFields: ["活动行详情页", "准确场馆", "主办方", "嘉宾/品牌名单", "票务信息", "官方图片"],
    contentSections: [{ title: "活动行列表摘要", body: "该活动匹配杭州电商品牌与新消费增长线索，适合继续深挖参会品牌。" }],
    updatedAt: "2026-06-28",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-hdx-005",
    title: "2026独立站私享会",
    city: "杭州",
    venue: "杭州，具体场馆待补充",
    type: "闭门会",
    rank: "B",
    status: "即将开始",
    startDate: "2026-07-30",
    endDate: "2026-07-30",
    industries: ["商场", "美妆", "食品饮料", "鞋服", "3C数码"],
    brands: ["独立站品牌", "DTC品牌", "跨境品牌", "品牌服务商"],
    host: "活动行公开活动页待补充",
    summary: "活动行公开列表出现“2026独立站私享会”。DTC和独立站品牌往往具备品牌化、线下体验和渠道验证需求，适合进入品牌线索池。",
    highlights: ["DTC品牌", "独立站", "闭门交流"],
    fitProducts: ["品牌合作", "快闪体验", "市场调研"],
    audience: ["DTC品牌", "跨境品牌", "品牌服务商", "独立站运营团队"],
    attendeeRoles: ["创始人", "品牌负责人", "增长负责人", "运营负责人"],
    representativeBrands: ["独立站品牌", "跨境DTC品牌"],
    scale: "私享会规模待补充",
    ticketInfo: "待补充活动行报名信息",
    participation: "建议作为杭州DTC品牌小型高密度线索活动，补报名条件后评估",
    buSuggestion: ["品牌BD", "快闪体验"],
    leadAngle: "围绕DTC品牌线下体验、快闪试卖、品牌联名和国内渠道测试切入。",
    mediaAccounts: ["活动行", "DTC/独立站行业媒体"],
    sourceType: "活动行",
    sourceConfidence: "高",
    source: "https://www.huodongxing.com/",
    sourceLabel: "活动行公开列表",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["活动行公开首页/列表出现该活动名称及排期线索。", "当前仅抓到列表级信息。"],
    lhbNotes: ["闭门会规模可能不大，但品牌负责人密度可能较高。"],
    missingFields: ["活动行详情页", "准确场馆", "主办方", "参会门槛", "票务信息", "官方图片"],
    contentSections: [{ title: "活动行列表摘要", body: "该活动偏小型品牌私享会，适合作为高密度品牌负责人触达线索。" }],
    updatedAt: "2026-06-28",
    isNew: true,
    isHeadline: false
  }
];
