window.MEDIA_ACTIVITIES = [
  {
    id: "evt-066",
    title: "2026 CCFA购物中心与奥特莱斯发展大会",
    city: "杭州",
    venue: "杭州",
    type: "峰会",
    rank: "S",
    status: "历史",
    startDate: "2026-06-24",
    endDate: "2026-06-25",
    industries: ["商场", "鞋服", "美妆", "食品饮料"],
    brands: ["购物中心", "奥特莱斯", "时尚零售品牌", "商业地产"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官方公众号已发布该大会成功召开信息。当前已确认主题方向为购物中心、奥特莱斯、时尚零售与消费发展，适合作为商业地产与品牌线下合作的重点跟进活动。",
    highlights: ["CCFA官方活动", "商业地产决策层", "杭州重点城市"],
    fitProducts: ["品牌引入", "空间招商", "IP快闪", "慢闪体验"],
    audience: ["购物中心", "奥特莱斯", "商业地产", "时尚零售品牌"],
    attendeeRoles: ["商业负责人", "招商负责人", "运营负责人", "品牌市场负责人"],
    representativeBrands: ["购物中心", "奥特莱斯", "时尚零售品牌"],
    scale: "CCFA年度重点会议，具体规模需补充参会名单与议程",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议补抓官方公众号文章与参会企业名单，形成商业地产BD线索池",
    buSuggestion: ["商场BD", "品牌引入", "活动专题"],
    leadAngle: "围绕购物中心存量焕新、品牌引入和IP快闪切入，重点寻找商场招商与品牌活动合作入口。",
    mediaAccounts: ["中国连锁经营协会", "CCFA", "商业地产行业媒体"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "高",
    source: "https://mp.weixin.qq.com/s/Hluc8tEcMqXYbRZ4-2Jl3g",
    sourceLabel: "CCFA官方公众号",
    image: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网新闻列表指向官方公众号文章，标题为“2026 CCFA购物中心与奥特莱斯发展大会、时尚零售与消费发展大会成功召开”。",
      "会议发生城市为杭州，活动时间按已抓取公开信息记录为2026年6月24-25日。",
      "主办方口径为中国连锁经营协会 CCFA，具体议程、嘉宾与参会企业名单仍需从公众号正文继续补全。"
    ],
    lhbNotes: [
      "优先核验购物中心、奥莱集团、品牌招商负责人名单，判断是否适合品牌引入、快闪/慢闪合作。",
      "如果官方正文含现场图和圆桌主题，应补充到图文资料，形成商业地产专题页。"
    ],
    missingFields: ["完整议程", "嘉宾名单", "参会企业名单", "官方现场图片", "报名/票务信息"],
    contentSections: [
      { title: "已确认信息", body: "该记录来自CCFA官方公众号线索，属于已发生的CCFA商业地产/零售方向会议；当前页面只展示已抓到的标题、城市、日期、主办方与业务匹配判断。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-067",
    title: "2026 CCFA时尚零售与消费发展大会",
    city: "杭州",
    venue: "杭州",
    type: "峰会",
    rank: "S",
    status: "历史",
    startDate: "2026-06-23",
    endDate: "2026-06-24",
    industries: ["鞋服", "美妆", "香氛", "商场"],
    brands: ["时尚零售品牌", "生活方式品牌", "购物中心", "消费品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官方公众号已发布“2026 CCFA时尚零售与消费发展大会在杭州...”相关信息。当前可确认这是面向时尚零售与消费发展的杭州线下会议，适合优先补充鞋服、美妆香氛、生活方式品牌线索。",
    highlights: ["CCFA官方活动", "时尚零售头部会议", "A类行业密集"],
    fitProducts: ["慢闪首店", "体验设计", "品牌合作", "市场调研"],
    audience: ["时尚零售品牌", "美妆香氛品牌", "商业地产", "渠道商"],
    attendeeRoles: ["品牌负责人", "市场负责人", "渠道负责人", "零售运营负责人"],
    representativeBrands: ["时尚零售品牌", "生活方式品牌", "购物中心"],
    scale: "CCFA年度重点会议，具体规模需补充官方议程",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议作为鞋服、美妆香氛品牌线索池，补抓嘉宾与参会企业",
    buSuggestion: ["鞋服BD", "美妆香氛BD", "体验设计"],
    leadAngle: "围绕时尚零售品牌线下体验升级和新店型测试切入，主推慢闪首店和体验设计。",
    mediaAccounts: ["中国连锁经营协会", "CCFA", "时尚商业媒体"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "高",
    source: "https://mp.weixin.qq.com/s/SFhVOsVyFaL3WYg6u3y6LA",
    sourceLabel: "CCFA官方公众号",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网新闻列表指向官方公众号文章，标题包含“2026 CCFA 时尚零售与消费发展大会在杭州”。",
      "会议城市为杭州，活动时间按已抓取公开信息记录为2026年6月23-24日。",
      "当前尚未补全官方正文中的议题、嘉宾、参会品牌与现场图片。"
    ],
    lhbNotes: [
      "重点查找服饰、美妆、香氛、生活方式品牌参会信息，沉淀可跟进的线下体验和首店需求。",
      "若官方文章出现品牌案例或渠道讨论，可拆成“品牌线下增长专题”。"
    ],
    missingFields: ["官方议程", "嘉宾/演讲企业", "参会品牌", "现场图片", "报名入口"],
    contentSections: [
      { title: "已确认信息", body: "该记录来自CCFA官方公众号线索，当前只确认活动名称、城市、日期、主办方和行业方向；品牌与议题详情需继续补正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-068",
    title: "2026 CCFA特许加盟大会&生活服务业发展大会",
    city: "北京",
    venue: "北京",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2026-05-28",
    endDate: "2026-05-29",
    industries: ["茶饮连锁", "餐厅", "食品饮料", "商场"],
    brands: ["连锁加盟品牌", "生活服务品牌", "餐饮品牌", "茶饮品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官方公众号已发布该大会在北京举行信息。活动方向覆盖特许加盟与生活服务业，和LHB的连锁品牌拓店、选址、竞品监测线索高度相关，但具体参会品牌仍需补全。",
    highlights: ["CCFA官方活动", "连锁加盟决策层", "北京重点城市"],
    fitProducts: ["数智化选址", "竞品监测", "招商线索", "市场调研"],
    audience: ["连锁餐饮", "茶饮品牌", "生活服务品牌", "加盟品牌"],
    attendeeRoles: ["创始人", "加盟负责人", "拓展负责人", "渠道负责人"],
    representativeBrands: ["连锁加盟品牌", "餐饮品牌", "茶饮品牌"],
    scale: "CCFA年度重点会议，具体规模需补官方议程",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议按餐饮/茶饮/生活服务拆分目标品牌清单",
    buSuggestion: ["数智化选址", "茶饮餐饮BD", "数据服务"],
    leadAngle: "围绕连锁品牌拓店、加盟布局和网点规划切入，主推数智化选址与竞品监测。",
    mediaAccounts: ["中国连锁经营协会", "CCFA", "连锁经营媒体"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "高",
    source: "https://mp.weixin.qq.com/s/krrRP48U1qHSl6gO15ldYw",
    sourceLabel: "CCFA官方公众号",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网新闻列表指向官方公众号文章，标题为“2026CCFA特许加盟大会&生活服务业发展大会在京举行”。",
      "会议城市为北京，活动时间按已抓取公开信息记录为2026年5月28-29日。",
      "当前尚未补全官方正文中的议程、参会品牌、嘉宾和现场图。"
    ],
    lhbNotes: [
      "优先识别餐饮、茶饮、生活服务连锁品牌的加盟拓展负责人。",
      "适合转化为数智化选址、竞品监测、城市开店节奏研究的线索池。"
    ],
    missingFields: ["官方议程", "嘉宾名单", "参会品牌", "现场图片", "票务/报名信息"],
    contentSections: [
      { title: "已确认信息", body: "该记录来自CCFA官方公众号线索，当前页面保留已确认的城市、日期、主办方与活动方向，不补写未核验的品牌名单。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-069",
    title: "GDMS全球数字营销峰会",
    city: "上海",
    venue: "国家会展中心（上海）",
    type: "峰会",
    rank: "S",
    status: "历史",
    startDate: "2025-09-16",
    endDate: "2025-09-17",
    industries: ["美妆", "香氛", "食品饮料", "3C数码", "鞋服"],
    brands: ["品牌广告主", "消费品牌", "数字营销服务商", "媒体平台"],
    host: "GDMS全球数字营销峰会",
    summary: "GDMS官网明确展示全球数字营销峰会定位、累计观看/参与数据、嘉宾来源和2025线下会场信息。该活动适合沉淀品牌营销负责人、消费品牌线下体验与内容转化线索。",
    highlights: ["品牌营销头部峰会", "国家会展中心上海", "品牌广告主密集"],
    fitProducts: ["品牌合作", "快闪体验", "体验设计", "活动专题"],
    audience: ["品牌广告主", "美妆香氛品牌", "食品饮料品牌", "3C品牌", "营销服务商"],
    attendeeRoles: ["CMO", "品牌负责人", "市场负责人", "媒介负责人"],
    representativeBrands: ["李宁", "腾讯智慧零售", "乐高", "联想集团", "亿滋国际"],
    scale: "官网介绍：累计线上线下观看500万+、品牌营销人参与5万+、815位营销决策层分享",
    ticketInfo: "以GDMS官网报名信息为准",
    participation: "建议作为品牌市场负责人线索池，重点记录线下体验与活动营销需求",
    buSuggestion: ["品牌合作", "内容专题", "体验设计"],
    leadAngle: "围绕品牌营销从内容到线下体验的转化切入，寻找快闪、新品体验和场景活动合作机会。",
    mediaAccounts: ["GDMS全球数字营销峰会", "品牌营销行业媒体", "广告门"],
    sourceType: "官网/公开网页",
    sourceConfidence: "高",
    source: "https://www.gdmschina.com/about",
    sourceLabel: "GDMS官网",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "GDMS官网介绍其为品牌营销年度头部峰会，并展示线上线下观看500万+、品牌营销人参与5万+、815位营销决策层主题分享等累计数据。",
      "GDMS官网会场页显示2025年活动时间为9月16-17日，地点为国家会展中心（上海）。",
      "官网公开信息出现的品牌/机构包括李宁、腾讯智慧零售、威富集团、亿滋国际、乐高、联想集团、网易、冰希黎、极萌、上美股份、小罐茶等。"
    ],
    lhbNotes: [
      "优先筛选有新品发布、线下体验、城市巡展、内容种草到门店转化需求的消费品牌。",
      "建议把GDMS作为品牌市场负责人线索池，而不是传统展商名录型活动。"
    ],
    missingFields: ["2026场次日期", "完整议程", "报名/票价", "官方现场图片授权", "可联系品牌名单"],
    contentSections: [
      { title: "官方信息摘要", body: "GDMS官网已确认峰会定位、累计规模数据、2025上海线下会场与部分品牌/机构线索；当前页面不再补写未确认的完整议程。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-070",
    title: "2026 CCFA零售CEO闭门会",
    city: "上海",
    venue: "上海，具体场馆待补充",
    type: "闭门会",
    rank: "S",
    status: "筹备中",
    startDate: "2026-11-16",
    endDate: "2026-11-18",
    industries: ["商场", "食品饮料", "美妆", "鞋服", "茶饮连锁"],
    brands: ["零售企业", "连锁品牌", "消费品牌", "商业地产"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页明确列出“11月16-18日 上海 零售CEO闭门会”为即将召开活动。该类闭门会决策层密度高，适合作为LHB头部商务线索与品牌引入专题候选。",
    highlights: ["CCFA即将召开", "CEO/决策层密度高", "上海重点城市"],
    fitProducts: ["品牌引入", "活动专题", "数智化选址", "品牌合作"],
    audience: ["零售企业", "连锁品牌", "商业地产", "消费品牌"],
    attendeeRoles: ["CEO", "创始人", "董事长", "业务负责人"],
    representativeBrands: ["零售企业", "连锁品牌", "消费品牌"],
    scale: "闭门会规模待公众号正文或报名页补充",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议优先作为头部活动跟进，补齐参会门槛、报名方式和参会企业名单",
    buSuggestion: ["品牌引入", "商场BD", "数据服务", "活动专题"],
    leadAngle: "以“品牌线下增长与门店网络升级”切入，优先争取会前获取参会企业名单并筛选高潜品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/Gbr_jGg_kMdSbMaTxyZp9Q",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表明确展示：【即将召开】11月16-18日 上海 零售CEO闭门会。",
      "来源链接指向CCFA官方公众号文章，但当前自动抓取触发微信环境验证，正文内容待补。",
      "活动城市上海、时间11月16-18日、活动类型闭门会可由CCFA首页确认。"
    ],
    lhbNotes: [
      "决策层闭门会适合获取品牌拓店、渠道升级、线下体验预算等高价值线索。",
      "需要优先补参会企业名单，否则商业化动作只能先定位为头部曝光和会前BD预热。"
    ],
    missingFields: ["具体场馆", "参会企业名单", "报名门槛", "议程主题", "官方现场图片"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页即将召开列表，当前确认城市、日期、活动名称和官方来源入口；公众号正文需后续人工验证或授权抓取。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-071",
    title: "2026 CCFA零售创新大会",
    city: "上海",
    venue: "上海，具体场馆待补充",
    type: "峰会",
    rank: "S",
    status: "筹备中",
    startDate: "2026-11-16",
    endDate: "2026-11-18",
    industries: ["商场", "3C数码", "食品饮料", "美妆", "鞋服"],
    brands: ["零售企业", "数字化服务商", "消费品牌", "商业地产"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页明确列出“11月16-18日 上海 零售创新大会”为即将召开活动。该活动适合覆盖零售创新、消费品牌、商业地产与数字化服务场景。",
    highlights: ["CCFA即将召开", "零售创新议题", "上海重点城市"],
    fitProducts: ["活动专题", "品牌合作", "体验设计", "数智化选址"],
    audience: ["零售企业", "消费品牌", "商业地产", "数字化服务商"],
    attendeeRoles: ["品牌负责人", "运营负责人", "渠道负责人", "数字化负责人"],
    representativeBrands: ["零售品牌", "连锁品牌", "数字化服务商"],
    scale: "大会规模待公众号正文或报名页补充",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议作为上海零售创新专题核心活动，补齐议程和嘉宾后做重点曝光",
    buSuggestion: ["活动专题", "品牌合作", "数据服务", "体验设计"],
    leadAngle: "围绕零售创新、线下体验、数字化选址和品牌渠道升级切入，筛选具有门店升级诉求的消费品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/Gbr_jGg_kMdSbMaTxyZp9Q",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表明确展示：【即将召开】11月16-18日 上海 零售创新大会。",
      "来源链接指向CCFA官方公众号文章，自动抓取时触发微信环境验证，正文待补。",
      "活动城市上海、时间11月16-18日、活动类型峰会可由CCFA首页确认。"
    ],
    lhbNotes: [
      "可作为上海零售创新专题的头部入口，服务曝光、线索收集和会后复盘。",
      "需要补议程主题后再拆分美妆、鞋服、食品饮料、3C等行业线索。"
    ],
    missingFields: ["具体场馆", "官方议程", "嘉宾名单", "参会品牌", "报名/票价"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页即将召开列表，当前确认城市、日期、活动名称和官方来源入口；内容详情需继续补正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-072",
    title: "2026 CCFA消费品渠道创新峰会及选品会",
    city: "杭州",
    venue: "杭州，具体场馆待补充",
    type: "选品会",
    rank: "A",
    status: "历史",
    startDate: "2026-04-15",
    endDate: "2026-04-16",
    industries: ["食品饮料", "美妆", "香氛", "鞋服", "商场"],
    brands: ["消费品品牌", "渠道商", "零售企业", "新消费品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页明确列出“4月15-16日 杭州 消费品渠道创新峰会及选品会”为已闭幕活动。该活动适合补充消费品牌渠道、选品、零售合作与线下拓展线索。",
    highlights: ["CCFA已闭幕", "消费品选品", "杭州重点城市"],
    fitProducts: ["品牌合作", "市场调研", "快闪体验", "渠道线索"],
    audience: ["消费品品牌", "渠道商", "零售采购", "新消费品牌"],
    attendeeRoles: ["渠道负责人", "采购负责人", "品牌负责人", "市场负责人"],
    representativeBrands: ["食品饮料品牌", "美妆香氛品牌", "生活方式品牌"],
    scale: "选品会规模待官方正文补充",
    ticketInfo: "以CCFA官方信息为准",
    participation: "建议作为历史活动复盘，补参会品牌和选品方向后形成杭州消费品线索池",
    buSuggestion: ["品牌合作", "美妆香氛BD", "食品饮料BD", "市场调研"],
    leadAngle: "围绕渠道创新和选品合作切入，寻找具备线下测试、快闪试卖和商场入驻意愿的消费品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/Gbr_jGg_kMdSbMaTxyZp9Q",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表明确展示：【已闭幕】4月15-16日 杭州 消费品渠道创新峰会及选品会。",
      "来源链接指向CCFA官方公众号文章，自动抓取时触发微信环境验证，正文待补。",
      "活动城市杭州、时间4月15-16日、活动形态峰会及选品会可由CCFA首页确认。"
    ],
    lhbNotes: [
      "选品会天然适合发现新消费品牌、渠道合作和线下试卖需求。",
      "后续应优先补品牌/采购名单，用于生成可跟进客户表。"
    ],
    missingFields: ["具体场馆", "参会品牌", "采购/渠道方名单", "官方图文", "选品品类"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页已闭幕列表，当前确认城市、日期、活动名称和官方来源入口；详细选品方向需补正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-073",
    title: "2026 CCFA全零售AI火花大会",
    city: "杭州",
    venue: "杭州，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2026-04-15",
    endDate: "2026-04-16",
    industries: ["商场", "3C数码", "食品饮料", "美妆", "鞋服"],
    brands: ["零售企业", "消费品牌", "AI服务商", "数字化服务商"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页明确列出“4月15-16日 杭州 全零售AI火花大会”为已闭幕活动。该活动适合观察AI在零售选址、会员运营、门店效率和营销内容中的应用。",
    highlights: ["CCFA已闭幕", "AI零售议题", "杭州重点城市"],
    fitProducts: ["数智化选址", "市场调研", "活动专题", "数据服务"],
    audience: ["零售企业", "消费品牌", "AI服务商", "商业地产"],
    attendeeRoles: ["数字化负责人", "运营负责人", "市场负责人", "渠道负责人"],
    representativeBrands: ["零售企业", "消费品牌", "AI服务商"],
    scale: "大会规模待官方正文补充",
    ticketInfo: "以CCFA官方信息为准",
    participation: "建议作为历史活动复盘，补议程后提炼AI零售与线下业务结合案例",
    buSuggestion: ["数据服务", "数智化选址", "活动专题", "市场调研"],
    leadAngle: "围绕AI零售、门店效率、选址模型和线下营销转化切入，筛选有数字化预算的零售品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/1eV2Bkik3yE-s3SNEbn_aw",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表明确展示：【已闭幕】4月15-16日 杭州 全零售AI火花大会。",
      "来源链接指向CCFA官方公众号文章，自动抓取时触发微信环境验证，正文待补。",
      "活动城市杭州、时间4月15-16日、AI零售主题可由CCFA首页确认。"
    ],
    lhbNotes: [
      "该活动可为LHB的数据服务、数智化选址和零售洞察产品提供议题支撑。",
      "需要补具体议程与案例，避免泛化成AI大会。"
    ],
    missingFields: ["具体场馆", "议程主题", "嘉宾/案例企业", "官方图文", "报名信息"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页已闭幕列表，当前确认城市、日期、活动名称、主题方向和官方来源入口；详细案例需补正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-074",
    title: "2026 CCFA特许加盟展",
    city: "北京",
    venue: "北京，具体场馆待补充",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2026-05-28",
    endDate: "2026-05-29",
    industries: ["茶饮连锁", "餐厅", "食品饮料", "商场"],
    brands: ["特许加盟品牌", "连锁餐饮", "茶饮品牌", "生活服务品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页公开新闻列出“2026特许加盟展在北京开幕”。该展会与特许加盟大会同城同期，适合补充连锁餐饮、茶饮和生活服务品牌拓店线索。",
    highlights: ["CCFA官方新闻", "加盟拓展场景", "北京重点城市"],
    fitProducts: ["数智化选址", "竞品监测", "招商线索", "市场调研"],
    audience: ["特许加盟品牌", "连锁餐饮", "茶饮品牌", "生活服务品牌"],
    attendeeRoles: ["加盟负责人", "拓展负责人", "创始人", "渠道负责人"],
    representativeBrands: ["茶饮品牌", "餐饮品牌", "生活服务品牌"],
    scale: "展会规模待官方正文补充",
    ticketInfo: "以CCFA官方报名信息为准",
    participation: "建议与特许加盟大会合并跟进，重点补品牌名单和加盟拓展负责人",
    buSuggestion: ["数智化选址", "茶饮餐饮BD", "数据服务"],
    leadAngle: "围绕加盟拓店、城市网点规划和竞品分布切入，优先识别正处于扩张期的连锁品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/JhCKQwoUQ73kVLDdTgD5zg",
    sourceLabel: "CCFA官方公众号",
    image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页新闻列表展示“2026特许加盟展在北京开幕”。",
      "该来源指向CCFA官方公众号文章，自动抓取时可能触发微信验证，正文待补。",
      "活动与2026CCFA特许加盟大会&生活服务业发展大会处于同一北京线索组。"
    ],
    lhbNotes: [
      "展会更适合直接找扩张品牌和加盟招商负责人。",
      "可与特许加盟大会数据合并，形成北京连锁拓店线索专题。"
    ],
    missingFields: ["准确场馆", "展商名单", "展会规模", "票务信息", "官方现场图片"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页新闻线索，当前确认活动名称、城市和官方公众号来源；具体规模与参展品牌待补。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-075",
    title: "2025亿邦动力品牌与跨境电商线下大会",
    city: "杭州",
    venue: "杭州世纪澜宴宴会中心",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-06-06",
    endDate: "2025-06-06",
    industries: ["食品饮料", "3C数码", "商场", "美妆"],
    brands: ["跨境电商品牌", "AI原生品牌", "平台方", "服务商"],
    host: "亿邦动力",
    summary: "本地参考表记录该亿邦动力线下活动于2025年6月6日在杭州世纪澜宴宴会中心举办，覆盖品牌方、跨境电商平台、AI原生品牌与服务商，适合补充品牌增长和线下转化线索。",
    highlights: ["亿邦动力具体场次", "杭州重点城市", "品牌与平台资源"],
    fitProducts: ["品牌合作", "市场调研", "活动专题", "慢闪体验"],
    audience: ["跨境电商品牌", "AI原生品牌", "平台方", "营销服务商"],
    attendeeRoles: ["CEO", "CMO", "CTO", "出海业务负责人", "平台商业化负责人"],
    representativeBrands: ["TCL智能家庭", "绝味食品", "阿里巴巴国际站", "TikTok Shop", "亚马逊全球开店"],
    scale: "本地参考表记录：线下1200+人参与，线上直播覆盖",
    ticketInfo: "本地参考表记录：1999元/人",
    participation: "建议补官网/公众号原文后，作为杭州品牌增长与跨境电商资源专题收录",
    buSuggestion: ["品牌合作", "内容专题", "数据服务", "市场调研"],
    leadAngle: "从跨境品牌的线下展示、AI营销和品牌体验需求切入，筛选适合做慢闪店或城市体验活动的消费品牌。",
    mediaAccounts: ["亿邦动力", "亿邦动力网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "本地参考表记录：活动时间为2025.6.6，地点为杭州世纪澜宴宴会中心，主办方为亿邦动力。",
      "参考表记录参会方包括跨境电商品牌、AI原生品牌、阿里巴巴国际站、TikTok Shop、亚马逊全球开店及服务商。",
      "参考表记录代表信息包括TCL智能家庭、绝味食品相关分享线索，线下1200+人参与，票价1999元/人。"
    ],
    lhbNotes: [
      "亿邦动力适合作为品牌零售、电商、跨境与AI营销方向的重要媒体源继续跟踪。",
      "该活动更偏品牌增长和平台资源，不应简单归为展会，适合做品牌线索与活动专题。"
    ],
    missingFields: ["官方活动页", "完整活动名称", "完整议程", "官方图片", "报名页链接"],
    contentSections: [
      { title: "本地参考表摘要", body: "该记录来自本地Excel参考表，字段包含日期、城市、场馆、主办方、参会人群、代表品牌、规模与票价；后续需补亿邦官网或公众号原文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-076",
    title: "2025刀法品牌增长线下大会",
    city: "广州",
    venue: "广州，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "筹备中",
    startDate: "2025-12-18",
    endDate: "2025-12-19",
    industries: ["美妆", "香氛", "食品饮料", "鞋服", "3C数码"],
    brands: ["新消费品牌", "成熟消费品牌", "大健康品牌", "营销平台"],
    host: "刀法研究所",
    summary: "本地参考表记录刀法相关线下活动计划于2025年12月18-19日在广州举行，覆盖消费品牌、营销平台和服务商，是用户点名需要重点补充的品牌增长媒体活动源。",
    highlights: ["刀法具体场次", "消费品牌决策层", "广州重点城市"],
    fitProducts: ["品牌合作", "慢闪体验", "活动专题", "市场调研"],
    audience: ["新消费品牌", "成熟消费品牌", "大健康品牌", "平台方", "营销服务商"],
    attendeeRoles: ["创始人", "CEO", "CMO", "CPO", "市场总监", "平台负责人"],
    representativeBrands: ["图拉斯", "左点", "迪卡侬", "浴见", "欧莱雅", "元气森林", "完美日记"],
    scale: "本地参考表记录：预计线下参会人数1000+，线上直播覆盖",
    ticketInfo: "本地参考表记录：2399元/人、5299元/人、18999元/人",
    participation: "建议优先补刀法研究所公众号原文、嘉宾议程和报名页，作为消费品牌增长专题核心活动",
    buSuggestion: ["品牌合作", "美妆香氛BD", "内容专题", "慢闪体验"],
    leadAngle: "围绕消费品牌增长、线下体验转化和品牌人社交资源切入，重点寻找有新品发布、体验活动和城市巡展需求的品牌。",
    mediaAccounts: ["刀法研究所", "刀法Digipont"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "本地参考表记录：刀法活动时间为2025.12.18-19，城市广州，主办方为刀法研究所，来源指向微信公众号刀法研究所。",
      "参考表记录参会人群包括新消费品牌、成熟品牌、大健康品牌、巨量引擎、小红书等平台及营销机构。",
      "参考表记录代表品牌包括图拉斯、左点、迪卡侬、浴见、欧莱雅、元气森林、完美日记，预计线下1000+人。"
    ],
    lhbNotes: [
      "刀法是消费品牌增长和营销负责人密度较高的重点来源，应作为后续公众号抓取优先级。",
      "适合沉淀美妆、香氛、食品饮料、运动鞋服品牌的慢闪/快闪线下体验需求。"
    ],
    missingFields: ["官方活动页", "准确场馆", "完整议程", "嘉宾名单", "官方图片"],
    contentSections: [
      { title: "本地参考表摘要", body: "该记录来自本地Excel参考表，已具备日期、城市、主办方、参会人群、代表品牌、规模和票价线索；仍需用刀法公众号或报名页复核。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: true
  },
  {
    id: "evt-077",
    title: "2026 CCFA零售业供应链大会",
    city: "武汉",
    venue: "武汉，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2026-05-25",
    endDate: "2026-05-27",
    industries: ["食品饮料", "商场", "茶饮连锁"],
    brands: ["零售企业", "供应链企业", "连锁商超", "消费品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页活动列表明确列出“5月25-27日 武汉 供应链大会”为已闭幕活动。虽然不在首批五城，但零售供应链与品牌渠道、选品、商超合作高度相关，纳入“其他”城市筛选。",
    highlights: ["CCFA官方活动", "供应链与零售渠道", "其他城市高匹配"],
    fitProducts: ["品牌合作", "市场调研", "渠道线索", "数据服务"],
    audience: ["零售企业", "供应链企业", "连锁商超", "消费品牌"],
    attendeeRoles: ["供应链负责人", "采购负责人", "渠道负责人", "品牌负责人"],
    representativeBrands: ["零售企业", "连锁商超", "食品饮料品牌"],
    scale: "CCFA年度供应链活动，规模待官方正文补充",
    ticketInfo: "以CCFA官方信息为准",
    participation: "建议作为其他城市高匹配活动收录，补参会企业后用于零售渠道线索",
    buSuggestion: ["品牌合作", "市场调研", "数据服务"],
    leadAngle: "从供应链、渠道采购和零售选品切入，寻找需要线下测试、渠道拓展和区域门店合作的消费品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/ILHxE4dhZboBy1qvrgoMZQ",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表展示：【已闭幕】5月25-27日 武汉 供应链大会。",
      "来源链接指向CCFA官方公众号文章，正文自动抓取可能触发微信验证。",
      "活动城市武汉不在首批重点五城，已纳入城市筛选“其他”。"
    ],
    lhbNotes: [
      "该活动适合从零售渠道和供应链角度补品牌线索，不作为首页头部专题优先。",
      "需要补参会品牌和采购方名单后，才能转为BD线索表。"
    ],
    missingFields: ["具体场馆", "参会企业名单", "议程", "官方图片", "报名信息"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页已闭幕列表，当前确认城市、日期、活动名称和官方来源入口；详细内容待补公众号正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-078",
    title: "2026 CCFA便利店大会",
    city: "长沙",
    venue: "长沙，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2026-05-20",
    endDate: "2026-05-22",
    industries: ["食品饮料", "茶饮连锁", "商场"],
    brands: ["便利店", "连锁零售", "食品饮料品牌", "即时零售平台"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页活动列表明确列出“5月20-22日 长沙 便利店大会”为已闭幕活动。便利店大会适合补充食品饮料、新消费品牌、即时零售与渠道拓展线索。",
    highlights: ["CCFA官方活动", "便利店渠道", "其他城市高匹配"],
    fitProducts: ["渠道线索", "市场调研", "品牌合作", "数智化选址"],
    audience: ["便利店企业", "食品饮料品牌", "渠道商", "即时零售平台"],
    attendeeRoles: ["采购负责人", "渠道负责人", "运营负责人", "品牌负责人"],
    representativeBrands: ["便利店连锁", "食品饮料品牌", "即时零售平台"],
    scale: "CCFA便利店方向重点活动，规模待官方正文补充",
    ticketInfo: "以CCFA官方信息为准",
    participation: "建议作为食品饮料和便利店渠道线索补充，后续补参会企业名单",
    buSuggestion: ["食品饮料BD", "数据服务", "市场调研"],
    leadAngle: "围绕便利店渠道、即饮即食新品、区域铺货和门店网络模型切入，服务食品饮料品牌线下增长。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/YsFH3cQeT6ufcm04YLF63Q",
    sourceLabel: "CCFA首页活动入口",
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页活动列表展示：【已闭幕】5月20-22日 长沙 便利店大会。",
      "来源链接指向CCFA官方公众号文章，正文自动抓取可能触发微信验证。",
      "活动城市长沙不在首批重点五城，已纳入城市筛选“其他”。"
    ],
    lhbNotes: [
      "便利店大会适合作为食品饮料、茶饮周边和即时零售品牌的渠道线索来源。",
      "需补品牌名单后判断是否适合数智化选址和区域铺店服务。"
    ],
    missingFields: ["具体场馆", "参会品牌", "便利店企业名单", "议程", "官方图片"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页已闭幕列表，当前确认城市、日期、活动名称和官方来源入口；详细内容待补公众号正文。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-079",
    title: "2026 CCFA零售业自有品牌大会",
    city: "合肥",
    venue: "合肥，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    industries: ["食品饮料", "美妆", "家居家装", "商场"],
    brands: ["零售自有品牌", "商超", "供应链企业", "消费品品牌"],
    host: "中国连锁经营协会 CCFA",
    summary: "CCFA官网首页新闻列表明确出现“2026 CCFA零售业自有品牌大会在合肥召开”。该活动适合观察商超自有品牌、消费品供应链和渠道合作机会。",
    highlights: ["CCFA官方活动", "零售自有品牌", "其他城市高匹配"],
    fitProducts: ["品牌合作", "渠道线索", "市场调研", "数据服务"],
    audience: ["零售企业", "商超", "供应链企业", "消费品品牌"],
    attendeeRoles: ["采购负责人", "品牌负责人", "供应链负责人", "渠道负责人"],
    representativeBrands: ["商超自有品牌", "食品饮料供应链", "美妆个护供应链"],
    scale: "CCFA自有品牌方向大会，规模待官方正文补充",
    ticketInfo: "以CCFA官方信息为准",
    participation: "建议作为其他城市高匹配活动收录，补充自有品牌和供应链企业名单",
    buSuggestion: ["品牌合作", "市场调研", "食品饮料BD"],
    leadAngle: "围绕商超自有品牌、消费品供应链和渠道共创切入，寻找具备线下试卖和渠道扩张需求的品牌。",
    mediaAccounts: ["中国连锁经营协会", "CCFA"],
    sourceType: "公众号/行业媒体",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/LRrf0ZD_Sn_BQiJLDS03zQ",
    sourceLabel: "CCFA官方公众号",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "CCFA官网首页新闻列表展示“2026 CCFA零售业自有品牌大会在合肥召开”。",
      "来源链接指向CCFA官方公众号文章，正文自动抓取可能触发微信验证。",
      "活动城市合肥不在首批重点五城，已纳入城市筛选“其他”。"
    ],
    lhbNotes: [
      "自有品牌大会能帮助识别商超渠道和消费品供应链合作机会。",
      "若补到参会品牌，可用于食品饮料、美妆个护和家居日用品线索池。"
    ],
    missingFields: ["准确日期核验", "具体场馆", "参会品牌", "议程", "官方图片"],
    contentSections: [
      { title: "已确认信息", body: "该活动来自CCFA官网首页新闻列表，当前确认活动名称、城市和官方公众号来源；日期按首页已闭幕活动列表记录为6月10-11日。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-080",
    title: "2025世界服装大会",
    city: "东莞",
    venue: "广东东莞虎门，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-16",
    endDate: "2025-11-17",
    industries: ["鞋服", "商场"],
    brands: ["服装品牌", "鞋服渠道", "服装产业带", "设计师品牌"],
    host: "世界服装鞋帽网等行业媒体线索",
    summary: "本地参考表媒体源记录“2025世界服装大会（2025年11月16-17日，广东东莞虎门）”。该活动不在首批五城，但鞋服产业匹配度高，适合作为其他城市补充活动。",
    highlights: ["鞋服高匹配", "产业带城市", "本地参考表媒体源"],
    fitProducts: ["品牌合作", "慢闪体验", "市场调研", "渠道线索"],
    audience: ["服装品牌", "鞋服渠道", "产业带企业", "设计师品牌"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "设计负责人", "市场负责人"],
    representativeBrands: ["服装品牌", "鞋服渠道商", "产业带企业"],
    scale: "规模待官方活动页补充",
    ticketInfo: "待补充",
    participation: "建议作为鞋服行业其他城市活动源补充，后续核验官网/公众号",
    buSuggestion: ["鞋服BD", "品牌合作", "市场调研"],
    leadAngle: "围绕鞋服品牌的渠道增长、线下体验和商场合作切入，寻找有城市快闪和首店测试需求的品牌。",
    mediaAccounts: ["世界服装鞋帽网", "服装行业媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表媒体源",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80"
    ],
    sourceFacts: [
      "本地参考表媒体源记录：2025世界服装大会，时间为2025年11月16-17日，地点为广东东莞虎门。",
      "该记录来自世界服装鞋帽网相关媒体源条目，仍需官网或公众号二次核验。",
      "活动城市东莞不在首批重点五城，已纳入城市筛选“其他”。"
    ],
    lhbNotes: [
      "鞋服是LHB A类优先行业，产业带会议可补充品牌和渠道线索。",
      "该记录缺官方页，暂不进入头部专题，但适合进入其他城市活动库。"
    ],
    missingFields: ["官方活动页", "主办方核验", "具体场馆", "嘉宾名单", "报名信息"],
    contentSections: [
      { title: "本地参考表摘要", body: "该记录来自本地Excel媒体源条目，已具备活动名称、时间、城市和行业方向；后续需补官网/公众号验证。" }
    ],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-081",
    title: "2026成都建博会",
    city: "成都",
    venue: "成都，具体展馆待补充",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2026-04-16",
    endDate: "2026-04-18",
    industries: ["家居家装", "商场", "设计装饰"],
    brands: ["家居建材品牌", "门窗卫浴品牌", "定制家居", "装企"],
    host: "中国建筑材料流通协会、Informa markets 英富曼会展集团",
    summary: "本地参考表记录成都建博会2026年规划16万㎡展区、预计2000+家参展企业、18万+专业观众，是中西部家居建材与慢闪店场地需求的重要线索。",
    highlights: ["中西部家居建材旗舰展", "2000+参展企业", "18万+专业观众"],
    fitProducts: ["慢闪体验", "品牌合作", "渠道线索", "体验设计"],
    audience: ["家居经销商", "制造生产厂家", "房地产开发商", "装饰工程公司", "行业媒体"],
    attendeeRoles: ["企业高管", "经销商", "代理商", "设计师", "工程负责人"],
    representativeBrands: ["皇派门窗", "龙牌", "千年舟", "兔宝宝", "海尔", "美的"],
    scale: "2026年规划160000㎡展区，预计2000+家参展企业，50000+款新品，180000+人次专业观众，50+场论坛/新品发布会",
    ticketInfo: "待补充官方报名/门票信息",
    participation: "建议作为成都家居建材慢闪需求重点活动，补官网后筛选品牌与装企线索",
    buSuggestion: ["家居BD", "慢闪体验", "品牌合作"],
    leadAngle: "围绕家居建材新品推广、场景化体验和中西部区域拓店切入，寻找慢闪店与体验空间需求。",
    mediaAccounts: ["成都建博会", "中国建筑材料流通协会", "家居行业媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：成都建博会时间为4月16日-18日，城市成都，主办方为中国建筑材料流通协会、Informa markets 英富曼会展集团。", "参考表记录2026年规划160000㎡展区、预计2000+家参展企业、180000+人次专业观众。"],
    lhbNotes: ["成都可补强西南家居建材线索。", "需补官方活动页和参展品牌名单。"],
    missingFields: ["官方活动页", "准确场馆", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "字段包含时间、城市、主办方、规模、目标人群和LHB慢闪店切入角度，需官网二次核验。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-082",
    title: "2025南京第六届快消品全渠道新增长大会",
    city: "南京",
    venue: "江苏南京银城皇冠假日酒店",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-10-15",
    endDate: "2025-10-17",
    industries: ["食品饮料", "便利店", "商场", "茶饮连锁"],
    brands: ["快消品牌", "渠道商", "便利店", "零食折扣品牌"],
    host: "安得智联、销售与市场杂志社",
    summary: "本地参考表记录该大会覆盖快消品牌、渠道商与科技服务商，参会1500+人、展商100+，适合补充食品饮料与渠道增长线索。",
    highlights: ["快消渠道增长", "1500+参会", "100+展商"],
    fitProducts: ["渠道线索", "品牌合作", "市场调研", "慢闪试卖"],
    audience: ["品牌商", "渠道商", "科技服务商", "金融机构"],
    attendeeRoles: ["营销总监", "CEO", "供应链负责人", "创始人"],
    representativeBrands: ["青岛饮料集团", "零食有鸣", "馋不二", "山东银座", "美宜佳"],
    scale: "参会1500+人，展商数量100+",
    ticketInfo: "待补充",
    participation: "建议作为南京快消与便利店渠道线索收录",
    buSuggestion: ["食品饮料BD", "渠道线索", "市场调研"],
    leadAngle: "围绕快消品牌渠道增长、便利店/零食折扣铺货和线下试卖切入。",
    mediaAccounts: ["销售与市场", "安得智联"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：2025.10.15-10.17，南京银城皇冠假日酒店。", "参会1500+人，展商数量100+，代表企业含青岛饮料集团、零食有鸣、美宜佳等。"],
    lhbNotes: ["适合补食品饮料和便利店渠道线索。", "需补报名页和完整嘉宾议程。"],
    missingFields: ["官方活动页", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动字段完整度较高，已具备城市、场馆、主办方、代表企业、规模和岗位线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-083",
    title: "2025苏州华夏家博会",
    city: "苏州",
    venue: "苏州国际博览中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-21",
    endDate: "2025-11-23",
    industries: ["家居家装", "商场"],
    brands: ["家电品牌", "家具家居", "瓷砖卫浴", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录苏州华夏家博会覆盖家用电器、家具家居、瓷砖卫浴等品类，展览面积约30000+㎡、展商1500+、观众20000+。",
    highlights: ["苏州家居展", "1500+展商", "慢闪店匹配"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "装修公司", "经销商", "家电品牌"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家电品牌", "家具家居品牌", "综合建材品牌"],
    scale: "展览面积30000+㎡，展商数量1500+家，观众数量20000+人",
    ticketInfo: "待补充",
    participation: "建议作为苏州家居慢闪和装修公司线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕家居品牌线下获客、慢闪体验和区域展会场景合作切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/21-11/23，苏州国际博览中心。", "规模记录为30000+㎡、1500+展商、20000+观众。"],
    lhbNotes: ["可用于补充长三角非上海家居展会线索。"],
    missingFields: ["官方活动页", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，适合归入其他城市家居慢闪线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-084",
    title: "2025天津华夏家博会",
    city: "天津",
    venue: "天津梅江会展中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-07",
    endDate: "2025-11-09",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录天津华夏家博会展览面积40000+㎡、展商1500+、观众40000+，适合补充华北家居线下活动线索。",
    highlights: ["天津家居展", "1500+展商", "40000+观众"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "建材品牌"],
    scale: "展览面积40000+㎡，展商数量1500+家，观众数量40000+人",
    ticketInfo: "现场购票10元/张，网上申请免费领取门票",
    participation: "建议作为天津家居慢闪和渠道线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕家居家电区域获客、慢闪体验和装修公司合作切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/7-11/9，天津梅江会展中心。", "规模记录为40000+㎡、1500+展商、40000+观众。"],
    lhbNotes: ["可补充华北非北京城市活动库。"],
    missingFields: ["官方活动页", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，字段包含规模和票务信息。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-085",
    title: "2025鸿威重庆宠物博览会",
    city: "重庆",
    venue: "重庆国际博览中心",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-21",
    endDate: "2025-11-23",
    industries: ["宠物", "商场"],
    brands: ["宠物食品", "宠物用品", "宠物医疗", "宠物服务"],
    host: "广州世宠会展有限公司",
    summary: "本地参考表记录重庆宠物博览会展览面积36000+㎡、展商1200+、观众60000+，宠物品牌和线下消费场景匹配度高。",
    highlights: ["重庆宠物展", "1200+展商", "60000+观众"],
    fitProducts: ["品牌合作", "快闪体验", "市场调研"],
    audience: ["宠物食品品牌", "宠物用品品牌", "宠物医院", "宠物店"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "市场负责人"],
    representativeBrands: ["野性魅力", "博根拿", "倍内菲", "蓝氏", "猫太郎", "红狗"],
    scale: "展览面积36000+㎡，展商数量1200+家，观众数量60000+人",
    ticketInfo: "抖音搜索“重庆宠物展”购票；单人票29.9元，双人票49.9元",
    participation: "建议作为宠物行业重点补充活动，筛选宠物食品与用品品牌",
    buSuggestion: ["宠物BD", "品牌合作", "快闪体验"],
    leadAngle: "围绕宠物品牌线下体验、商场宠物活动和快闪试卖切入。",
    mediaAccounts: ["重庆宠物展", "世界宠物博览会"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/Munl_HNBCLyHc1enKwG1Yg",
    sourceLabel: "本地参考表/公众号线索",
    image: "https://images.unsplash.com/photo-1601758175576-648226072e90?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/21-11/23，重庆国际博览中心。", "规模记录为36000+㎡、1200+展商、60000+观众，票价29.9/49.9元。"],
    lhbNotes: ["宠物是当前覆盖偏少的B类行业，该活动有助于补齐品类。"],
    missingFields: ["官方活动页正文", "完整展商名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动字段包含场馆、票价、参会人群、代表品牌和规模，适合作为重庆宠物线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-086",
    title: "2025COE宁波国际户外用品博览会",
    city: "宁波",
    venue: "宁波国际会展中心",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-26",
    endDate: "2025-11-28",
    industries: ["运动户外", "鞋服", "商场"],
    brands: ["户外装备", "露营品牌", "水上运动品牌", "户外电子产品"],
    host: "宁波华贸国际展览有限公司",
    summary: "本地参考表记录宁波国际户外用品博览会覆盖户外装备、水上运动、露营及运动用品，是补充运动户外行业的重要其他城市活动。",
    highlights: ["户外用品", "宁波会展", "运动户外补强"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["户外品牌", "渠道商", "露营品牌", "运动用品企业"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人"],
    representativeBrands: ["原始人", "迪飞客", "牧游人", "露营盒子"],
    scale: "本地参考表记录可接触大量户外行业潜在客户，具体规模待补",
    ticketInfo: "参考表含领票链接，需复核",
    participation: "建议作为运动户外其他城市活动补充，补展商名单后跟进品牌",
    buSuggestion: ["运动户外BD", "慢闪体验"],
    leadAngle: "围绕户外品牌城市体验、露营场景快闪和运动用品线下试用切入。",
    mediaAccounts: ["宁波国际户外用品博览会", "户外行业媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "http://nboutdoorfair.com/",
    sourceLabel: "宁波户外展官网线索",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/26-11/28，宁波国际会展中心。", "展品包括户外装备、水上运动、户外电子、露营及运动用品。"],
    lhbNotes: ["运动户外是A类优先行业，宁波可补充非一线城市品牌渠道。"],
    missingFields: ["官方详情页", "规模", "展商名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动具备城市、场馆、官网线索和展品方向，适合作为运动户外补充源。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-087",
    title: "2025第四届厦门国际咖啡产业博览会",
    city: "厦门",
    venue: "厦门国际会展中心B3-B5馆",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-21",
    endDate: "2025-11-23",
    industries: ["茶饮连锁", "食品饮料", "商场"],
    brands: ["咖啡品牌", "茶饮品牌", "烘焙品牌", "餐饮设备品牌"],
    host: "待补充",
    summary: "本地参考表记录厦门国际咖啡产业博览会在厦门国际会展中心举办，覆盖咖啡、茶饮、烘焙与餐饮设备方向，适合补充餐饮茶饮类线下品牌线索。",
    highlights: ["咖啡产业", "茶饮餐饮", "厦门补充城市"],
    fitProducts: ["品牌合作", "快闪试卖", "市场调研", "慢闪体验"],
    audience: ["咖啡品牌", "茶饮连锁", "餐饮渠道商", "设备服务商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "门店运营负责人"],
    representativeBrands: ["咖啡品牌", "茶饮品牌", "烘焙品牌"],
    scale: "本地参考表暂未记录规模，需补充官方展商和观众数据",
    ticketInfo: "待补充官方报名/门票信息",
    participation: "建议用于茶饮咖啡新品牌线索补充，重点核验参展品牌与招商合作入口",
    buSuggestion: ["茶饮餐饮BD", "快闪试卖", "品牌合作"],
    leadAngle: "围绕咖啡茶饮新品试饮、商场快闪、区域开店与品牌联名活动切入。",
    mediaAccounts: ["咖啡行业媒体", "厦门会展"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：2025第四届厦门国际咖啡产业博览会，时间11/21-11/23，地点厦门国际会展中心B3-B5馆。"],
    lhbNotes: ["茶饮餐饮是LHB重点匹配行业，厦门可补足东南沿海其他城市线索。", "需优先补官方图文、展商名单和票务入口。"],
    missingFields: ["官方活动页", "主办方", "规模", "展商名单", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该记录已具备活动名称、时间、城市和展馆，适合作为茶饮咖啡行业的其他城市补充线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-088",
    title: "2025厦门国际鞋业博览会",
    city: "厦门",
    venue: "厦门国际博览中心",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-27",
    endDate: "2025-11-29",
    industries: ["鞋服", "运动户外", "商场"],
    brands: ["鞋履品牌", "运动鞋品牌", "服饰品牌", "鞋材供应链"],
    host: "广州广旅展览策划有限公司",
    summary: "本地参考表记录厦门国际鞋业博览会为鞋服方向展会，与LHB鞋服、运动户外和商场品牌线索匹配度较高。",
    highlights: ["鞋业展会", "鞋服品牌线索", "厦门补充城市"],
    fitProducts: ["慢闪体验", "品牌合作", "渠道线索"],
    audience: ["鞋履品牌", "运动鞋品牌", "鞋材供应商", "渠道商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人"],
    representativeBrands: ["鞋履品牌", "运动鞋品牌", "鞋材供应链企业"],
    scale: "本地参考表未记录规模，需补官方数据",
    ticketInfo: "待补充",
    participation: "建议作为鞋服行业其他城市活动补充，优先补展商名单后跟进品牌",
    buSuggestion: ["鞋服BD", "慢闪体验"],
    leadAngle: "围绕鞋服新品体验、城市首店、运动场景快闪和渠道招商切入。",
    mediaAccounts: ["鞋业行业媒体", "厦门会展"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/27-11/29，厦门国际博览中心，主办方广州广旅展览策划有限公司。"],
    lhbNotes: ["鞋服是优先行业，该活动适合补充区域鞋履品牌和供应链线索。"],
    missingFields: ["官方活动页", "规模", "展商名单", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动匹配鞋服和运动户外方向，当前信息以本地表格为准，后续需公众号/官网复核。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-089",
    title: "2025青岛华夏家博会",
    city: "青岛",
    venue: "青岛国际会展中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-28",
    endDate: "2025-11-30",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录青岛华夏家博会展览面积25000+㎡、展商1500+、观众30000+，可补充山东家居家装线下线索。",
    highlights: ["青岛家居展", "1500+展商", "30000+观众"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "综合建材品牌"],
    scale: "展览面积25000+㎡，展商数量1500+家，观众数量30000+人",
    ticketInfo: "现场购票10元/张，网上申请免费领取门票",
    participation: "建议作为山东区域家居慢闪线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕家居家电新品体验、装修获客和区域快闪合作切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/28-11/30，青岛国际会展中心。", "规模记录为25000+㎡、1500+展商、30000+观众。"],
    lhbNotes: ["可补山东及环渤海家居品牌线索。"],
    missingFields: ["官方活动页", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，字段含场馆、票务和规模。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-090",
    title: "2025华夏家博会无锡站",
    city: "无锡",
    venue: "无锡太湖国际博览中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-12-05",
    endDate: "2025-12-07",
    industries: ["家居家装", "商场"],
    brands: ["家用电器", "家具家居", "瓷砖卫浴", "地板门窗", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录无锡华夏家博会覆盖家电、家具、瓷砖卫浴、地板门窗与综合建材，是长三角家居线索补充活动。",
    highlights: ["无锡家居展", "家装家电", "长三角补充"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家用电器品牌", "家具家居品牌", "瓷砖卫浴品牌"],
    scale: "本地参考表暂未记录规模，需补官方展商和观众数据",
    ticketInfo: "待补充",
    participation: "建议作为无锡及苏南家居家装品牌线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕苏南家居品牌区域营销、商场快闪与装修获客切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：12/5-12/7，无锡太湖国际博览中心。", "展品包括家用电器、家具家居、瓷砖卫浴、地板门窗、综合建材。"],
    lhbNotes: ["无锡可补充长三角非上海/杭州家居活动。"],
    missingFields: ["官方活动页", "规模", "参展品牌名单", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，当前保留为中可信补充记录。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-091",
    title: "2025行业之光大会暨第34届全国建材与家居行业年会",
    city: "佛山",
    venue: "佛山，具体场馆待补充",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-12-10",
    endDate: "2025-12-11",
    industries: ["家居家装", "商场"],
    brands: ["建材品牌", "家居品牌", "卖场", "家电头部企业"],
    host: "中国建筑材料流通协会",
    summary: "本地参考表记录行业之光大会为全国建材与家居行业年会，预计覆盖500+行业领袖与企业代表，适合作为家居建材高价值决策层线索。",
    highlights: ["建材家居年会", "行业协会主办", "决策层线索"],
    fitProducts: ["品牌合作", "慢闪体验", "渠道线索"],
    audience: ["建材家居生产企业", "卖场", "经销商代理商", "装饰装修企业", "家装电商平台", "设计师", "家电企业"],
    attendeeRoles: ["行业领袖", "企业代表", "协会负责人", "渠道负责人"],
    representativeBrands: ["九牧集团", "圣象集团", "居然之家", "红星美凯龙"],
    scale: "预计超500位行业领袖、企业代表参会，吸引数千名专业观众关注",
    ticketInfo: "待补充",
    participation: "建议作为家居建材决策层线索重点补充，补议程后用于品牌合作BD",
    buSuggestion: ["家居BD", "品牌合作", "渠道线索"],
    leadAngle: "围绕家居建材品牌新品推广、卖场合作、慢闪体验和渠道资源对接切入。",
    mediaAccounts: ["中国建筑材料流通协会", "泛家居行业媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：2025年12月，佛山，主办方中国建筑材料流通协会。", "参会人群含建材家居企业、卖场、经销商、装饰装修企业、家装电商平台、设计师和家电头部企业。"],
    lhbNotes: ["协会型年会具备较强商务对接价值，需补官方议程和报名入口后可提升评级。"],
    missingFields: ["官方活动页", "准确场馆", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动字段覆盖主办方、参会人群、代表品牌、规模和LHB切入角度，建议后续重点核验。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-092",
    title: "2025第二届中部武汉礼业博览会",
    city: "武汉",
    venue: "武汉客厅-中国文化博览中心",
    type: "展会",
    rank: "A",
    status: "历史",
    startDate: "2025-11-14",
    endDate: "2025-11-16",
    industries: ["食品饮料", "3C数码", "商场", "鞋服"],
    brands: ["礼品品牌", "食品品牌", "智能家居", "文创产品", "服饰箱包"],
    host: "仁创会展集团",
    summary: "本地参考表记录武汉礼业博览会覆盖食品、厨具杯壶、智能家居、文创、服饰箱包等品类，展出面积30000+㎡、展商500+、观众30000+。",
    highlights: ["礼品渠道", "500+展商", "商超百货观众"],
    fitProducts: ["品牌合作", "渠道线索", "快闪试卖"],
    audience: ["大型商超", "精品连锁店", "百货公司", "书店", "礼品渠道商"],
    attendeeRoles: ["采购负责人", "渠道负责人", "品牌负责人", "礼品渠道商"],
    representativeBrands: ["食品品牌", "智能家居品牌", "文创品牌", "服饰箱包品牌"],
    scale: "展出面积30000+㎡，展商数量500+家，观众数量30000+人",
    ticketInfo: "待补充",
    participation: "建议用于商超礼品渠道、文创和食品品牌线索补充",
    buSuggestion: ["食品饮料BD", "渠道线索", "品牌合作"],
    leadAngle: "围绕礼品渠道、百货商超采购、文创食品快闪和品牌渠道铺设切入。",
    mediaAccounts: ["仁创会展集团", "武汉礼品展"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/YGD_SRty8yRaWSYke7exjw",
    sourceLabel: "本地参考表/公众号线索",
    image: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/14-11/16，武汉客厅-中国文化博览中心。", "品类含坚果炒货、酒水食品、茶叶、特色农产品、厨具杯壶、智能家居、文创产品、服饰箱包。"],
    lhbNotes: ["礼品展虽非核心行业名称，但食品、文创、智能家居、百货渠道与LHB线下业务有交集。"],
    missingFields: ["官方活动页正文", "完整展商名单", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动对接商超、百货、精品连锁和书店渠道，适合补充食品饮料、文创和智能家居线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-093",
    title: "2025成都天府家博会",
    city: "成都",
    venue: "成都世纪城新国际会展中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-21",
    endDate: "2025-11-23",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录成都天府家博会展览面积50000+㎡、展商1200+、观众35000+，适合补充成都家居慢闪场景线索。",
    highlights: ["成都家博会", "1200+展商", "35000+观众"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "建材品牌"],
    scale: "展览面积50000+㎡，展商数量1200+家，观众数量35000+人",
    ticketInfo: "现场购票10元/张，网上申请免费领取门票",
    participation: "建议作为成都家居线索补充，和成都建博会形成双活动覆盖",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕家居家电新品体验、区域获客和慢闪空间合作切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "https://mp.weixin.qq.com/s/4bY2iN-bQBE28BlJrYCeYA",
    sourceLabel: "本地参考表/公众号线索",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/21-11/23，成都世纪城新国际会展中心。", "规模记录为50000+㎡、1200+展商、35000+观众。"],
    lhbNotes: ["成都为西南核心消费城市，该活动补充家居家装慢闪需求。"],
    missingFields: ["官方活动页正文", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动具备时间、场馆、规模和票务线索，适合作为成都家居线索补充。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-094",
    title: "2025郑州华夏家博会",
    city: "郑州",
    venue: "郑州国际家博会",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-22",
    endDate: "2025-11-23",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录郑州华夏家博会展览面积40000+㎡、展商1500+、观众100000+，可作为中原区域家居家装线索补充。",
    highlights: ["郑州家居展", "1500+展商", "100000+观众"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "综合建材品牌"],
    scale: "展览面积40000+㎡，展商数量1500+家，观众数量100000+人",
    ticketInfo: "待补充",
    participation: "建议作为中原区域家居慢闪线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕家居品牌区域拓客、商场慢闪和装修公司合作切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/22-11/23，郑州国际家博会。", "规模记录为40000+㎡、1500+展商、100000+观众。"],
    lhbNotes: ["郑州可补中原家居家装品牌和渠道客户。"],
    missingFields: ["官方活动页", "准确场馆信息", "票务信息", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，规模较大但仍需官方页复核。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-095",
    title: "2025中国零售业高质量发展大会",
    city: "南昌",
    venue: "赣江新区国际会展中心",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-08-17",
    endDate: "2025-08-17",
    industries: ["商场", "食品饮料", "3C数码"],
    brands: ["零售企业", "科技服务商", "金融机构", "商超品牌"],
    host: "中国商业股份制企业经济联合会、赣江招商发展集团、华夏荣耀控股集团",
    summary: "本地参考表记录该大会覆盖零售企业、科技服务商、金融机构、政府与协会，参会500余人、展商50+，适合补充零售与商超渠道线索。",
    highlights: ["零售高质量发展", "500+参会", "50+展商"],
    fitProducts: ["渠道线索", "品牌合作", "市场调研"],
    audience: ["零售企业", "科技服务商", "金融机构", "政府与协会"],
    attendeeRoles: ["商务部门代表", "零售企业CEO", "品牌总监", "科技创始人"],
    representativeBrands: ["苏州人民商场", "华夏荣耀控股"],
    scale: "500余人，展商数量50+家",
    ticketInfo: "待补充",
    participation: "建议用于零售企业和商超渠道线索补充",
    buSuggestion: ["商场BD", "渠道线索", "品牌合作"],
    leadAngle: "围绕零售企业线下活动、商超渠道合作和可计算开店服务切入。",
    mediaAccounts: ["中国商业股份制企业经济联合会", "零售行业媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：2025.08.17，江西南昌赣江新区国际会展中心。", "覆盖零售企业、科技服务商、金融机构、政府与协会，参会500余人、展商50+。"],
    lhbNotes: ["零售大会有助于触达商超和区域零售企业，可补非一线城市商场渠道线索。"],
    missingFields: ["官方活动页", "完整嘉宾名单", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动具备时间、地点、主办方、参会人群和规模信息，适合作为零售渠道补充源。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-096",
    title: "2025台州华夏家博会",
    city: "台州",
    venue: "台州国际博览中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-07",
    endDate: "2025-11-09",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录台州华夏家博会在台州国际博览中心举办，可补充浙江非杭州家居家装区域活动线索。",
    highlights: ["台州家居展", "浙江补充城市", "慢闪店匹配"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "建材品牌"],
    scale: "本地参考表暂未记录规模",
    ticketInfo: "现场购票10元/张，网上申请免费领取门票",
    participation: "建议作为浙江区域家居线索补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕浙江区域家居品牌线下获客、慢闪展示和装修渠道切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/7-11/9，台州国际博览中心。"],
    lhbNotes: ["用于补充浙江省内其他城市活动，不作为头部专题优先项。"],
    missingFields: ["官方活动页", "规模", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动当前信息较轻，保留为其他城市补充记录，后续需二次核验。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-097",
    title: "2025廊坊华夏家博会",
    city: "廊坊",
    venue: "廊坊国际会展中心",
    type: "展会",
    rank: "B",
    status: "历史",
    startDate: "2025-11-14",
    endDate: "2025-11-16",
    industries: ["家居家装", "商场"],
    brands: ["家居品牌", "家电品牌", "装修公司", "综合建材"],
    host: "华夏家博会",
    summary: "本地参考表记录廊坊华夏家博会展览面积30000+㎡、展商1000+、观众20000+，可补充京津冀家居家装线索。",
    highlights: ["廊坊家居展", "1000+展商", "京津冀补充"],
    fitProducts: ["慢闪体验", "品牌合作", "市场调研"],
    audience: ["家居品牌", "家电品牌", "装修公司", "建材经销商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "销售负责人"],
    representativeBrands: ["家居品牌", "家电品牌", "建材品牌"],
    scale: "展览面积30000+㎡，展商数量1000+家，观众数量20000+人",
    ticketInfo: "现场购票10元/张，网上申请免费领取门票",
    participation: "建议作为京津冀非北京家居活动补充",
    buSuggestion: ["家居BD", "慢闪体验"],
    leadAngle: "围绕京津冀家居品牌区域营销、商场快闪和装修获客切入。",
    mediaAccounts: ["华夏家博会", "展讯网"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：11/14-11/16，廊坊国际会展中心。", "规模记录为30000+㎡、1000+展商、20000+观众。"],
    lhbNotes: ["廊坊作为京津冀补充城市，适合沉淀家居行业区域线索。"],
    missingFields: ["官方活动页", "参展品牌名单", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该活动来自华夏家博会系列线索，规模信息相对完整，仍需官方图文补强。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-098",
    title: "2025中国区域零售企业创新论坛",
    city: "武汉",
    venue: "武汉光谷凯悦酒店",
    type: "峰会",
    rank: "A",
    status: "历史",
    startDate: "2025-09-18",
    endDate: "2025-09-20",
    industries: ["商场", "食品饮料", "便利店"],
    brands: ["区域连锁商超", "供应链服务商", "零售数字化企业"],
    host: "深圳市科脉技术股份有限公司、深圳市零售商业行业协会",
    summary: "本地参考表记录该论坛聚焦区域连锁商超、供应链与服务商，参会300+、展商50+，可直接触达零售企业决策层。",
    highlights: ["区域零售", "商超渠道", "300+决策层"],
    fitProducts: ["渠道线索", "品牌合作", "市场调研"],
    audience: ["区域连锁商超", "供应链服务商", "零售数字化企业"],
    attendeeRoles: ["连锁商超董事长", "总经理", "商品采购负责人", "数字化转型负责人"],
    representativeBrands: ["华豫佰佳", "折扣牛", "武汉中百仓储"],
    scale: "参会人数300+，展商数量50+",
    ticketInfo: "待补充",
    participation: "建议作为华中商超渠道线索补充，重点跟进区域连锁零售企业",
    buSuggestion: ["商场BD", "渠道线索", "品牌合作"],
    leadAngle: "围绕商超品牌活动、区域开店、快闪试卖和零售数字化选址切入。",
    mediaAccounts: ["科脉", "深圳市零售商业行业协会", "智慧零售媒体"],
    sourceType: "本地参考表",
    sourceConfidence: "中",
    source: "2025～2026线下行业峰会、展会表.xlsx",
    sourceLabel: "本地参考表",
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["本地参考表记录：2025.9.18-9.20，武汉光谷凯悦酒店。", "参会对象为区域连锁商超、供应链与服务商，参会300+、展商50+。"],
    lhbNotes: ["区域零售企业与LHB可计算开店和线下活动场景高度相关。"],
    missingFields: ["官方活动页", "完整议程", "票务信息", "官方图片"],
    contentSections: [{ title: "本地参考表摘要", body: "该论坛对接区域连锁商超决策层，适合作为武汉商超渠道线索补充。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-099",
    title: "2026成都世界宠物博览会",
    city: "成都",
    venue: "中国成都西部国际博览城",
    type: "展会",
    rank: "A",
    status: "进行中",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    industries: ["宠物", "商场"],
    brands: ["宠物食品", "宠物用品", "宠物服务", "宠物医疗"],
    host: "待补充",
    summary: "聚展网城市页记录成都世界宠物博览会于2026年6月26-28日在中国成都西部国际博览城举办，展览面积3.6万㎡、观众4万人、展商1200家，当前页面显示开展中。",
    highlights: ["成都宠物展", "1200家展商", "进行中活动"],
    fitProducts: ["快闪体验", "品牌合作", "市场调研"],
    audience: ["宠物品牌", "宠物渠道商", "宠物服务机构", "商场活动方"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "门店运营负责人"],
    representativeBrands: ["宠物食品品牌", "宠物用品品牌", "宠物服务品牌"],
    scale: "展览面积3.6万㎡，观众人数4万人，展商数量1200家",
    ticketInfo: "聚展网记录门票150元",
    participation: "建议作为宠物行业其他城市高优先线索，尽快补官方展商名单并筛选品牌",
    buSuggestion: ["宠物BD", "快闪体验", "品牌合作"],
    leadAngle: "围绕宠物品牌线下体验、商场宠物主题活动、宠物新品试卖和会员运营切入。",
    mediaAccounts: ["聚展网", "成都宠物展", "宠物行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-533-0-0-1/",
    sourceLabel: "聚展网四川展会页",
    image: "https://images.unsplash.com/photo-1601758175576-648226072e90?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网四川展会页记录：2026.06.26-06.28，中国成都西部国际博览城。", "页面记录展览面积3.6万㎡、观众4万人、展商1200家、门票150元。"],
    lhbNotes: ["宠物是LHB需要继续补强的行业，该活动规模和时效性都较好。"],
    missingFields: ["官方活动页", "主办方", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动是当前进行中的成都宠物线下展会，适合快速补品牌和渠道线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-100",
    title: "2026成都礼品及家居用品展-文创旅游商品展",
    city: "成都",
    venue: "成都世纪新城国际会展中心",
    type: "展会",
    rank: "A",
    status: "进行中",
    startDate: "2026-06-25",
    endDate: "2026-06-27",
    industries: ["家居家装", "潮玩", "IP类", "商场"],
    brands: ["礼品品牌", "家居用品", "文创品牌", "旅游商品"],
    host: "待补充",
    summary: "聚展网记录成都礼品及家居用品展-文创旅游商品展于2026年6月25-27日举办，展览面积2万㎡、观众4.2万人、展商500家，当前显示开展中。",
    highlights: ["文创旅游商品", "家居礼品", "进行中活动"],
    fitProducts: ["快闪体验", "品牌合作", "渠道线索"],
    audience: ["文创品牌", "家居用品品牌", "礼品渠道商", "商场运营方"],
    attendeeRoles: ["品牌负责人", "采购负责人", "渠道负责人"],
    representativeBrands: ["文创品牌", "家居礼品品牌", "旅游商品品牌"],
    scale: "展览面积2万㎡，观众人数4.2万人，展商数量500家",
    ticketInfo: "聚展网记录门票30元",
    participation: "建议补全文创/IP品牌清单后，用于商场快闪和伴手礼渠道合作",
    buSuggestion: ["IP/潮玩BD", "家居BD", "品牌合作"],
    leadAngle: "围绕文创IP快闪、商场节庆活动、旅游商品线下体验和家居礼品渠道切入。",
    mediaAccounts: ["聚展网", "成都礼品展", "文创行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-533-0-0-1/",
    sourceLabel: "聚展网四川展会页",
    image: "https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网四川展会页记录：2026.06.25-06.27，成都世纪新城国际会展中心。", "页面记录展览面积2万㎡、观众4.2万人、展商500家、门票30元。"],
    lhbNotes: ["礼品家居与文创IP适合商场快闪、品牌联名和渠道线索沉淀。"],
    missingFields: ["官方活动页", "主办方", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动具备家居、礼品、文创和旅游商品属性，是成都其他城市线索的高时效补充。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-101",
    title: "2026成都国际连锁加盟展览会",
    city: "成都",
    venue: "成都世纪新城国际会展中心",
    type: "展会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-07-02",
    endDate: "2026-07-04",
    industries: ["茶饮连锁", "食品饮料", "商场"],
    brands: ["连锁餐饮", "茶饮品牌", "零售品牌", "加盟品牌"],
    host: "SFE",
    summary: "聚展网记录成都国际连锁加盟展览会将于2026年7月2-4日举办，展览面积1.6万㎡、观众2.8万人、展商300家，距离开展约6天。",
    highlights: ["连锁加盟", "茶饮餐饮线索", "即将开始"],
    fitProducts: ["可计算开店", "渠道线索", "快闪试卖"],
    audience: ["连锁加盟品牌", "餐饮茶饮品牌", "零售品牌", "招商加盟服务商"],
    attendeeRoles: ["品牌创始人", "招商负责人", "渠道负责人", "运营负责人"],
    representativeBrands: ["连锁餐饮品牌", "茶饮品牌", "零售加盟品牌"],
    scale: "展览面积1.6万㎡，观众人数2.8万人，展商数量300家",
    ticketInfo: "聚展网记录门票30元",
    participation: "建议作为成都即将开始活动重点跟进，筛选茶饮餐饮与连锁零售品牌",
    buSuggestion: ["茶饮餐饮BD", "可计算开店", "渠道线索"],
    leadAngle: "围绕连锁品牌拓店、选址评估、商圈快闪试卖和招商获客切入。",
    mediaAccounts: ["聚展网", "SFE", "连锁加盟行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-533-0-0-1/",
    sourceLabel: "聚展网四川展会页",
    image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网四川展会页记录：2026.07.02-07.04，成都世纪新城国际会展中心。", "页面记录展览面积1.6万㎡、观众2.8万人、展商300家、门票30元。"],
    lhbNotes: ["连锁加盟活动与可计算开店、茶饮餐饮、品牌拓店高度相关。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动离当前日期很近，适合作为默认即将开始筛选下的其他城市补充活动。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-102",
    title: "2026中国国际家电与消费电子制造业供应链展览会",
    city: "宁波",
    venue: "宁波国际会展中心",
    type: "展会",
    rank: "A",
    status: "即将开始",
    startDate: "2026-08-05",
    endDate: "2026-08-07",
    industries: ["3C数码", "家居家装", "商场"],
    brands: ["家电品牌", "消费电子品牌", "智能家居供应链", "制造服务商"],
    host: "CAEE",
    summary: "聚展网记录中国国际家电与消费电子制造业供应链展览会将于2026年8月5-7日在宁波国际会展中心举办，展览面积3万㎡、观众5万人、展商500家。",
    highlights: ["家电消费电子", "宁波会展", "500家展商"],
    fitProducts: ["体验设计", "慢闪体验", "品牌合作", "渠道线索"],
    audience: ["家电品牌", "消费电子品牌", "供应链企业", "渠道商"],
    attendeeRoles: ["品牌负责人", "产品负责人", "渠道负责人", "采购负责人"],
    representativeBrands: ["家电品牌", "消费电子品牌", "智能硬件企业"],
    scale: "展览面积3万㎡，观众人数5万人，展商数量500家",
    ticketInfo: "聚展网记录开票提醒",
    participation: "建议作为3C数码/家电场景体验线索，补展商后筛选智能硬件品牌",
    buSuggestion: ["3C数码BD", "体验设计", "慢闪体验"],
    leadAngle: "围绕智能家电新品体验、消费电子线下展示和家居场景慢闪切入。",
    mediaAccounts: ["聚展网", "CAEE", "家电行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-527-1138-0-1/",
    sourceLabel: "聚展网宁波展会页",
    image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网宁波展会页记录：2026.08.05-08.07，宁波国际会展中心。", "页面记录展览面积3万㎡、观众5万人、展商500家。"],
    lhbNotes: ["3C数码和智能家居是LHB重要匹配行业，宁波数据可补其他城市即将开始活动。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动补齐宁波未来活动，适合消费电子与智能家居体验型线索沉淀。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-103",
    title: "2026武汉国际茶产业展-武汉茶博会",
    city: "武汉",
    venue: "武汉国际会展中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-09-11",
    endDate: "2026-09-14",
    industries: ["茶饮连锁", "食品饮料", "商场"],
    brands: ["茶品牌", "茶饮品牌", "食品渠道商", "茶器品牌"],
    host: "TEAEXPO",
    summary: "聚展网记录武汉国际茶产业展-武汉茶博会将于2026年9月11-14日举办，展览面积4.5万㎡、观众5万人、展商2000家，页面标记热门。",
    highlights: ["武汉茶博会", "2000家展商", "茶饮食品"],
    fitProducts: ["快闪试卖", "品牌合作", "渠道线索"],
    audience: ["茶品牌", "茶饮渠道商", "食品经销商", "商场采购"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "加盟负责人"],
    representativeBrands: ["茶品牌", "茶饮品牌", "茶器品牌"],
    scale: "展览面积4.5万㎡，观众人数5万人，展商数量2000家",
    ticketInfo: "聚展网记录限时免费",
    participation: "建议作为武汉茶饮食品线索重点储备，后续补公众号与展商名单",
    buSuggestion: ["茶饮餐饮BD", "品牌合作", "渠道线索"],
    leadAngle: "围绕茶饮新品试饮、商场茶文化快闪、渠道招商和区域开店切入。",
    mediaAccounts: ["聚展网", "TEAEXPO", "武汉茶博会"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-534-1219-0-1/",
    sourceLabel: "聚展网武汉展会页",
    image: "https://images.unsplash.com/photo-1563911892437-1feda0179e1b?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网武汉展会页记录：2026.09.11-09.14，武汉国际会展中心。", "页面记录展览面积4.5万㎡、观众5万人、展商2000家、限时免费。"],
    lhbNotes: ["茶饮食品与商场活动高相关，适合作为武汉未来活动储备。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动规模较大、行业匹配度高，目前距离开展超过45天，系统会归为筹备中。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-104",
    title: "2026中国武汉国际酒业博览会",
    city: "武汉",
    venue: "武汉国际博览中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-10-16",
    endDate: "2026-10-18",
    industries: ["食品饮料", "商场"],
    brands: ["酒水品牌", "食品饮料渠道商", "餐饮渠道", "商超渠道"],
    host: "CIADE",
    summary: "聚展网记录中国武汉国际酒业博览会将于2026年10月16-18日举办，展览面积8万㎡、观众10万人、展商1000家，门票限时免费。",
    highlights: ["酒水食品", "1000家展商", "10万观众"],
    fitProducts: ["快闪试卖", "品牌合作", "渠道线索"],
    audience: ["酒水品牌", "食品饮料经销商", "餐饮渠道商", "商超采购"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "招商负责人"],
    representativeBrands: ["酒水品牌", "食品饮料品牌", "渠道商"],
    scale: "展览面积8万㎡，观众人数10万人，展商数量1000家",
    ticketInfo: "聚展网记录限时免费",
    participation: "建议用于酒水食品品牌和商超渠道线索储备",
    buSuggestion: ["食品饮料BD", "渠道线索", "品牌合作"],
    leadAngle: "围绕酒水品牌快闪试饮、商场节庆活动、餐饮渠道合作和商超铺货切入。",
    mediaAccounts: ["聚展网", "CIADE", "酒业行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-534-1219-0-1/",
    sourceLabel: "聚展网武汉展会页",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网武汉展会页记录：2026.10.16-10.18，武汉国际博览中心。", "页面记录展览面积8万㎡、观众10万人、展商1000家、限时免费。"],
    lhbNotes: ["食品饮料品牌有快闪试饮和渠道拓展需求，适合作为华中储备活动。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动规模较大，适合后续在食品饮料线索池中持续跟踪。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-105",
    title: "2026华东美妆展-宁波美妆供应链博览会",
    city: "宁波",
    venue: "宁波国际会展中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-10-16",
    endDate: "2026-10-18",
    industries: ["美妆", "商场"],
    brands: ["美妆品牌", "个护品牌", "美妆供应链", "渠道商"],
    host: "CXBE",
    summary: "聚展网记录华东美妆展-宁波美妆供应链博览会将于2026年10月16-18日举办，展览面积3万㎡、观众2.5万人、展商600家。",
    highlights: ["美妆供应链", "600家展商", "宁波补充城市"],
    fitProducts: ["快闪体验", "品牌合作", "市场调研"],
    audience: ["美妆品牌", "个护品牌", "供应链企业", "渠道商"],
    attendeeRoles: ["品牌负责人", "市场负责人", "渠道负责人", "采购负责人"],
    representativeBrands: ["美妆品牌", "个护品牌", "供应链企业"],
    scale: "展览面积3万㎡，观众人数2.5万人，展商数量600家",
    ticketInfo: "聚展网记录门票30元",
    participation: "建议作为美妆行业其他城市活动补充，后续补品牌名单后筛选快闪需求",
    buSuggestion: ["美妆BD", "快闪体验", "品牌合作"],
    leadAngle: "围绕美妆新品体验、商场快闪、渠道招商和供应链品牌合作切入。",
    mediaAccounts: ["聚展网", "CXBE", "美妆行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-527-1138-0-1/",
    sourceLabel: "聚展网宁波展会页",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网宁波展会页记录：2026.10.16-10.18，宁波国际会展中心。", "页面记录展览面积3万㎡、观众2.5万人、展商600家、门票30元。"],
    lhbNotes: ["美妆为优先行业，该活动适合补齐非一线城市美妆供应链和渠道品牌。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动补充宁波美妆方向储备，当前距离开展超过45天，系统会归为筹备中。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  },
  {
    id: "evt-106",
    title: "2026长三角食品及酒饮渠道创新展览会",
    city: "合肥",
    venue: "合肥滨湖国际会展中心",
    type: "展会",
    rank: "A",
    status: "筹备中",
    startDate: "2026-11-27",
    endDate: "2026-11-29",
    industries: ["食品饮料", "茶饮连锁", "商场"],
    brands: ["食品品牌", "酒饮品牌", "渠道商", "零售品牌"],
    host: "FCIE",
    summary: "聚展网记录长三角食品及酒饮渠道创新展览会将于2026年11月27-29日在合肥滨湖国际会展中心举办，展览面积2万㎡、观众3万人、展商600家。",
    highlights: ["食品酒饮渠道", "600家展商", "长三角补充"],
    fitProducts: ["渠道线索", "快闪试卖", "品牌合作"],
    audience: ["食品品牌", "酒饮品牌", "零售渠道商", "餐饮渠道商"],
    attendeeRoles: ["品牌负责人", "渠道负责人", "采购负责人", "招商负责人"],
    representativeBrands: ["食品品牌", "酒饮品牌", "渠道商"],
    scale: "展览面积2万㎡，观众人数3万人，展商数量600家",
    ticketInfo: "聚展网记录门票30元",
    participation: "建议作为长三角食品酒饮渠道线索储备，补展商名单后重点筛品牌",
    buSuggestion: ["食品饮料BD", "渠道线索", "快闪试卖"],
    leadAngle: "围绕食品酒饮新品试吃试饮、商超渠道、商场快闪和区域品牌合作切入。",
    mediaAccounts: ["聚展网", "FCIE", "食品饮料行业媒体"],
    sourceType: "聚展网",
    sourceConfidence: "高",
    source: "https://www.jufair.com/exhibition-0-0-1-530-1148-0-1/",
    sourceLabel: "聚展网合肥展会页",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    sourceFacts: ["聚展网合肥展会页记录：2026.11.27-11.29，合肥滨湖国际会展中心。", "页面记录展览面积2万㎡、观众3万人、展商600家、门票30元。"],
    lhbNotes: ["食品酒饮是LHB线下活动强匹配行业，合肥可补长三角其他城市覆盖。"],
    missingFields: ["官方活动页", "完整展商名单", "官方图片"],
    contentSections: [{ title: "聚展网摘要", body: "该活动明确匹配食品酒饮渠道，适合作为其他城市储备线索。" }],
    updatedAt: "2026-06-27",
    isNew: true,
    isHeadline: false
  }
];
